- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
change CI/CD ref to prod-io
---
> initial devops cicd

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
add WORKDIR parameter to pipeline
according to
https://github.com/pagopa/azure-pipeline-templates/blob/master/templates/terraform-plan/template.yaml#L11
---
> Fix WORKINGDIR on CICD

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- .pre-commit-config.yaml
- .tflint.hcl
- README.md
update pre-commit checks
update azurerm plugin version
update readme
update PR template
Manual alignment with infrastructure template to receive latest improvement
---
> Merge infrastructure-template update (until commit 997fd78)

- src/core/function_publiceventdispatcher.tf
> [#IP-437] Fix subnet and url to connect to `fn-eucovidcert`

- src/core/function_publiceventdispatcher.tf
> [#IP-437] fix webhook url

- src/core/README.md
- src/core/appgateway.tf
- src/core/data.tf
- src/core/env/prod/terraform.tfvars
- src/core/resource_groups.tf
- src/core/security.tf
- src/core/variables.tf
Add custom waf policy for app io listeners
Add *io.italia.it listeners
Add logs to prod-sec
manage app gateway with multi listener
this pr needs https://github.com/pagopa/azurerm/pull/109
---
> Add custom firewall policy for app io app gateway listener

- src/core/dns_io_italia_it.tf
api.io.italia.it change ttl to default value
---
> api.io.italia.it change ttl

- src/core/README.md
- src/core/appgateway.tf
- src/core/env/prod/terraform.tfvars
- src/core/variables.tf
add application gateway monitoring
---
> add app gateway monitoring

- src/core/README.md
- src/core/apim.tf
- src/core/apim_io_backend_v1.tf
- src/core/redis_apim.tf
- remove redis_apim
- add required subscription for IO-PRODUCT
cost savings
---
> Temp remove unused resources (redis_apim)

- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/function_elt.tf
- Add `io-cosmosdb-profiles` topic to event hub
- Add `PROFILE_TOPIC_NAME` and `PROFILE_TOPIC_CONNECTION_STRING` env variables to fn-elt
Export to PDND
---
> [#IC-126] Add profiles topic to Event Hub

- src/core/.terraform.lock.hcl
- src/core/README.md
- src/core/eucovidcert.tf
- src/core/function_elt.tf
- src/core/main.tf
- src/core/variables.tf
- add eucovidcert avaibility alert
- upgrade to terraform provider 2.87.0
improve osservability and reduce noise
---
> add eucovid cert avaibility alert

- src/core/storage_api_replica.tf
> New storage api replica

- src/core/appgateway.tf
- src/core/env/prod/terraform.tfvars
- fix app gateway affinity cookie name
- scale in to from 6 to 4 app gateway min instances
terraform plan show unwanted changes
---
> fix-appgateway instances and cookie name

- src/core/README.md
- src/core/appgateway.tf
- src/core/storage_api_replica.tf
Still waiting to reconfigure the Logic app which queries the log analytics workspace in PROD-IO
---
> Disable appgw accesslogs

- src/core/appgateway.tf
- src/core/env/prod/terraform.tfvars
- src/core/security.tf
- src/core/selfcare.tf
- src/core/variables.tf
- add new listener on app gateway
- fix health check path on selfcare
expose selfcare backend apis
---
> [INFRA-378] Expose selfcare backend apis

- src/core/function_elt.tf
Add `SERVICEID_EXCLUSION_LIST` to fn-elt
---
> [#IC-154] add SERVICEID_EXCLUSION_LIST variable to fn-elt

- src/core/api/io_backend/app/v1/_swagger.json.tpl
- MVL legal-messages endpoint
It is required in order to expose MVL endpoints through APIM
---
> [#IC-67] Add MVL backend endpoints

- src/core/monitor.tf
- src/core/selfcare.tf
add healthchecks for all public endpoints
check SSL expiration and avaibility
---
> Add healthchecks to public endpoints

- src/core/monitor.tf
Add healthcheck for api-gad
missing api-gad check
---
> Add healthcheck for api-gad

- src/core/monitor.tf
- change response code to 400
400 is the expected response code for this endpoint when is missing client certificate
---
> Fix api-mtls http response code

- src/core/appgateway.tf
- src/core/selfcare.tf
see commit list
`SelfCare IO` will dynamically resolve public signature key to verify incoming IdentityToken. Env var `SELFCARE_IDP_ISSUER_JWT_SIGNATURE_KEY` is no longer needed, it will be removed in https://github.com/pagopa/io-infra/pull/68
---
> [#IC-160] Implement jwk signature verification on `SelfCare IO`

- src/core/appgateway.tf
- src/core/devportal.tf
- src/core/monitor.tf
- src/core/selfcare.tf
migrate devportal
cost savings
---
> [#INFRA-437] Migrate-devportal

- src/core/README.md
- src/core/cgn.tf
- src/core/private_dns_zones.tf
> CGN Redis with private endpoint

- src/core/README.md
- src/core/app_backend.tf
- src/core/variables.tf
migrate app backend autoscale settings
migration to io-infra
---
> migrate app backend autoscale

- src/core/README.md
- src/core/storage_api_replica.tf
remove iopstapireplica from terraform
---
> [#INFRA-476] Reomve iopstapireplica from terraform

- src/core/README.md
- src/core/app_backend.tf
- src/core/appgateway.tf
- src/core/data.tf
- add app backend web test
- upgrade app_service app_service_slot modules to add vnet_route_all (not enabled on app_service_slot)
migration from legacy repo
---
> add-webtest-app-backend

- src/core/README.md
- src/core/cgn.tf
> Cosmos db Cgn

- src/core/app_backend.tf
> Pointed uat cgn operator search functions

- src/core/README.md
- src/core/cgn.tf
> Cosmosdb cgn database

- .github/workflows/static_analysis.yml
- terraform static analysis to code reviews
Improve quality with automatic test automation
---
> Add terraform static analysis to code reviews

- src/core/README.md
- src/core/function_subscription_migrations.tf
- src/core/selfcare.tf
fix fn-slot errors
this PR depends on https://github.com/pagopa/azurerm/pull/167 https://github.com/pagopa/azurerm/pull/168
---
> Fix-fn-slot

- src/core/cgn.tf
- src/core/variables.tf
Added blob storage to cgn
Added blob storage to backup data due to legal reasons after a card deletion 
---
> [#IC-207] Added storage due to legal backup

- src/core/cgn.tf
- src/core/data.tf
> Sql cosmos db private endpoint

- src/core/api/cgn/policy.xml
- src/core/api/cgn/swagger.json.tmpl
- src/core/api/cgn/v1/_base_policy.xml
- src/core/api/cgn/v1/_swagger.json.tpl
- src/core/cgn.tf
> Apim api cgn merchant

- src/core/cgn.tf
> Apim role assignment for app service cgn onboarding portal

- src/core/README.md
- src/core/api/base_policy.xml
- src/core/api_product/cgn/policy.xml
- src/core/cgn.tf
@AleDore can you pls complete the policy and take a look the other settings?
---
> CGN Merchant Api

- src/core/.terraform.lock.hcl
- src/core/README.md
- src/core/cgn.tf
- src/core/main.tf
> app registration for cgn and role assingement.

- src/core/.terraform.lock.hcl
- src/core/cgn.tf
> Test cgn backend authentication with service principal

- src/core/cgn.tf
> Fix failing static analysis check

- src/core/function_subscription_migrations.tf
> [#IC-238] Add missing db definition for `io-service-migrations`

- src/core/function_subscription_migrations.tf
> [#IC-185] Add `APIM_SERVICE_NAME` value

- src/core/function_subscription_migrations.tf
* add `QUEUE_ADD_SERVICE_TO_MIGRATIONS` queue
When a `Service` change is red from change feed it's logged into `migrations` table. We need to dispatch such job to be processed async 
---
> [#IC-252]  Subscription migrations queues

- src/core/function_subscription_migrations.tf
* set proper service name in APIM config for `functions-subscription-migrations`
Bad config. We fixed it up right in the portal, we align the codebase with this PR
---
> [#IC-246] Fix APIM service name

- src/core/function_subscription_migrations.tf
To start over processing the entire `services` collection
---
> [#IC-252] Use new version of the lease

- src/psql/selfcare/subscription-migrations/migrations/db/V2__schema_fixed.sql
> [#IC-238] Fix table schema

- src/core/function_subscription_migrations.tf
> [#IC-252] Disable listener on staging

- src/core/function_subscription_migrations.tf
- src/psql/selfcare/subscription-migrations/migrations/db/V2__schema_fixed.sql
There was a typo in the migration script
---
> fix type in schemas

- src/core/cgn.tf
> Cosmos cgn collections

- src/core/app_backend.tf
Add second scale rule on cpu metrics
We observed an abnormal high CPU so we want add a second scale rule to stay more safe
---
> Add Cpu scale rules for app-backend

- src/core/cgn.tf
> CGN Scaling

- src/core/app_backend.tf
> set empty app settings

- src/core/app_backend.tf
- src/core/data.tf
- Switch pagopa-proxy prod to pagoPA
dismantle pagopa-proxy
---
> [IOPAY-504] Switch pagopa-proxy prod to pagoPA

- src/core/api/cgn/v1/_base_policy.xml
- src/core/api/io_backend/app/v1/_base_policy.xml
- src/core/api/io_backend/auth/v1/_base_policy.xml
- src/core/api/io_backend/bonus/v1/_base_policy.xml
- src/core/api/io_backend/bpd/v1/_base_policy.xml
- src/core/api/io_backend/cgn/v1/_base_policy.xml
- src/core/api/io_backend/eucovidcert/v1/_base_policy.xml
- src/core/api/io_backend/mitvoucher/v1/_base_policy.xml
- src/core/api/io_backend/myportal/v1/_base_policy.xml
- src/core/api/io_backend/notifications/v1/_base_policy.xml
- src/core/api/io_backend/pagopa/v1/_base_policy.xml
- src/core/api/io_backend/public/v1/_base_policy.xml
- src/core/api/io_backend/session/v1/_base_policy.xml
- src/core/apim.tf
- src/core/locals.tf
- src/core/main.tf
- apim policy changes for backend
allow round robin connection to appbackend 1,2 and not only a single connection
> Api-roundrobin-2-appbackend

- src/core/app_messages.tf
> Add function messages staging slot

- src/core/function_subscription_migrations.tf
See commit list
As we declared to use queues on #117, we need to create them
---
> [#IC-282] Create queues

- src/core/app_messages.tf
- src/core/env/prod/terraform.tfvars
- src/core/variables.tf
cost savings after CGN start
---
> Reduce scaling

- src/core/api/cgn_os/v1/_base_policy.xml
- src/core/api/cgn_os/v1/_swagger.json.tpl
- src/core/api_product/cgn_os/_base_policy.xml
- src/core/apim.tf
- src/core/apim_cgn_operator_search.tf
This PR expose CGN operator search functions to external SAS registered on API's Product
- Add named values for function-can-operator-search
- Add Operator Search APIM config and policies
This PR is needed in order to expose Operator Search API's via APIM
---
> [#IC-367] Expose OS through APIM

- src/core/app_backend.tf
- src/core/data.tf
- Add fn-app-messages links to io-backend
- Add Feature Flags for switching traffic between `fn-app` and new `fn-app-messages`
---
> [#IC-389] Add fn-app-messages links to io-backend

- src/core/app_backend.tf
> Switch fn-messages prod step 1

- src/core/app_backend.tf
> Migrate messages step2

- src/core/app_backend.tf
- src/core/app_messages.tf
- src/core/devportal.tf
- src/core/function_elt.tf
- src/core/function_messages_cqrs.tf
- src/core/function_publiceventdispatcher.tf
- src/core/function_service_cache.tf
- src/core/function_subscription_migrations.tf
- src/core/monitor.tf
- src/core/selfcare.tf
- src/core/vpn.tf
> Upgrade 2.9.0 to 2.9.1

- src/core/app_backend.tf
Add new ENV variable configuration `FIMS_BASE_PATH` into `io-backend`
The new parameter `FIMS_BASE_PATH` is required in https://github.com/pagopa/io-backend/pull/884.
---
> [#IC-372] Add new required FIMS_BASE_PATH env for FIMS

- src/core/function_elt.tf
add 2 instances to function_elt
---
> Scale out function_elt

- src/core/function_elt.tf
> Scale in fn-elt to 1 instance

- .gitignore
- src/core/README.md
- src/core/container_registry.tf
- src/core/private_dns_zones.tf
Add azure container registry
---
> Add Azure container registry

- src/core/app_messages.tf
- src/core/env/prod/terraform.tfvars
> Tuning autoscale masseges

- src/core/env/prod/terraform.tfvars
> Update app_messages_function_autoscale_default to 10

- src/core/app_messages.tf
- Add Feature Flag env variables
- Set `FF_TYPE` to `beta`
- Use same beta tester list used by io-backend
Enable `getMessageFromView` for beta tester
---
> Add Feature Flag env variables

- src/core/env/prod/terraform.tfvars
scale out app gateway to 8 instances
Dona con IO initiative
---
> Scale out app gateway

- src/core/function_elt.tf
Scale out fn-elt to max 3 due to new trigger
High CPU consumption
---
> Scale out fn-elt to 3 due to new trigger

- src/core/env/prod/terraform.tfvars
set baseline capacity for app gateway
---
> Scale down app gateway capacity

- src/core/99_variables.tf
- src/core/env/prod/terraform.tfvars
- src/core/network.tf
- src/core/private_dns_zones.tf
Add virtual networks for beta, prod01, prod02
---
> Add virtual networks for beta, prod01, prod02

- src/core/network.tf
> fix vnet rg name

- src/core/network.tf
- src/core/private_dns_zones.tf
Add vnet peerings and dns zone links
---
> Add vnet peerings and dns zone links

- src/core/selfcare.tf
Update JWT issue configuration due to https://github.com/pagopa/selfcare-dashboard-backend/pull/59
---
> [#IC-449] Update JWT issuer on SelfCareIO

- .devops/deploy-pipelines.yml
- src/aks/02_aks.tf
add aks maintenence window
---
> add aks maintenence window

- src/aks/.terraform.lock.hcl
- src/aks/02_aks.tf
- src/aks/03_ingress.tf
- src/aks/03_keda.tf
- src/aks/99_locals.tf
- src/aks/99_main.tf
- src/aks/99_variables.tf
- src/aks/env/weu-beta/terraform.tfvars
- src/aks/env/weu-prod01/terraform.tfvars
- src/aks/env/weu-prod02/terraform.tfvars
- src/aks/ingress/loadbalancer.yaml.tpl
add ingress and keda to aks
aks experiment
---
> Add ingress and keda to aks

- src/core/dns_io_italia_it.tf
> add txt for zendesk

- src/core/dns_io_italia_it.tf
Add dns spf for zendesk (also imported TXT record for @)
---
> Add dns spf for zendesk

- src/core/app_backend.tf
expired https cert, temp migrated to https://raw.githubusercontent.com/pagopa/spid-idp/main/spid-entities-idps.xml
---
> Fix idp list https expired

- src/core/function_elt.tf
Add a new environment variable containig the service ID used by Piattaforma Notifiche to send notification to citixen.
Add pn_service_id var
Identify messages coming from Piattaforma Notifiche
---
> [#ICC-83] Add pn_service_id to fn-elt

- src/core/app_messages.tf
Add a new environment variable containig the service ID used by Piattaforma Notifiche to send notification to citixen.
Add pn_service_id var
Identify messages coming from Piattaforma Notifiche
---
> [#ICC-81] Add pn_service_id to app-messages

- src/sign/README.md
- src/sign/data.tf
- src/sign/io_sign_func.tf
> Allow "apim" subnet to "io-sign" function

- src/core/apim.tf
- src/core/app_backend.tf
> Point to new operator search

- src/core/README.md
- src/core/private_dns_zones.tf
> Add new private dns zones mongo

- src/payments-common/01_network.tf
- src/payments-common/03_database.tf
- src/payments/05_resource_group.tf
> [#ICC-102] Add cosmos resources to Payment Updater

- src/payments-common/03_database.tf
- src/payments-common/README.md
- src/payments/01_network.tf
- src/payments/04_events.tf
- src/payments/99_variables.tf
- src/payments/README.md
- src/payments/env/weu-prod01/terraform.tfvars
> [#ICC-102] Add Event Hub for Payment updater

- src/core/README.md
- src/core/private_dns_zones.tf
> add eventhub private link

- .devops/backupa-apim-deploy-pipelines.yml
> Apim backup pipeline

- src/.template-common/01_monitor.tf
- src/.template-common/99_variables.tf
- src/.template-common/README.md
- src/.template-common/env/prod/terraform.tfvars
- src/messages-common/01_monitor.tf
- src/messages-common/99_variables.tf
- src/messages-common/README.md
- src/messages-common/env/prod/terraform.tfvars
- src/payments-common/01_monitor.tf
- src/payments-common/03_database.tf
- src/payments-common/99_variables.tf
- src/payments-common/README.md
- src/payments-common/env/prod/terraform.tfvars
- src/payments/04_events.tf
- src/payments/README.md
- src/profile-common/01_monitor.tf
- src/profile-common/99_variables.tf
- src/profile-common/README.md
- src/profile-common/env/prod/terraform.tfvars
> fix connections strings

- src/aks/05_dns.tf
- src/aks/README.md
> fix public dns resolution for private links overlap

- src/messages/01_network.tf
- src/messages/06_events.tf
- src/messages/99_variables.tf
- src/messages/env/weu-prod01/terraform.tfvars
- src/payments-common/04_events.tf
> [ICC-102] Add Event Hub for CQRS

- src/core/monitor.tf
- src/messages/README.md
- src/payments-common/README.md
> fix health checks monitor

- src/core/README.md
- src/sign/README.md
- src/sign/key_vault.tf
> fix cicd io-sign

- src/messages-common/05_apim.tf
- src/messages-common/99_locals.tf
- src/messages-common/README.md
> [#ICC-112] Add APIM ref to Messages with ThirPartyMessages User Group

- src/core/app_backend.tf
> add PN Third Party config

- src/messages-common/05_apim.tf
- src/messages-common/README.md
> [#ICC-148] Add ApiMessageReadAdvanced and ApiMessageWriteAdvanced to APIM groups

- src/core/README.md
- src/core/azure_devops_agent.tf
> Add load test agent

- src/core/app_backend.tf
> Fix spid login

- src/core/app_backend.tf
> [#IOCIT-86] Changed pn api env url to COLL env

- src/core/app_backend.tf
- [remove unused vault variables](https://github.com/pagopa/io-infra/pull/214/commits/3ada1e3c1e4e151bf647404bbb709fbd80ab74be)
- [concat fake test users with real ones](https://github.com/pagopa/io-infra/pull/214/commits/f2944ef156e4d706fc06020a9b160c874d50ab6d)
---
> [#ICC-178] Add real test user for PN messages

- src/aks/03_ingress.tf
- src/aks/99_variables.tf
- src/aks/README.md
- src/aks/env/weu-beta/terraform.tfvars
- src/aks/env/weu-prod01/terraform.tfvars
- src/aks/env/weu-prod02/terraform.tfvars
pin image and sha256 version from external resources
As security best practice we pin external resources with sha256
---
> Pin nginx ingress version as security best practice

- src/.template/02_namespace.tf
- src/.template/99_variables.tf
- src/.template/README.md
- src/.template/env/weu-beta/terraform.tfvars
- src/.template/env/weu-prod01/terraform.tfvars
- src/.template/env/weu-prod02/terraform.tfvars
- src/.template/templates/tls-cert.yaml.tpl
- src/messages/02_namespace.tf
- src/messages/99_variables.tf
- src/messages/README.md
- src/messages/env/weu-beta/terraform.tfvars
- src/messages/env/weu-prod01/terraform.tfvars
- src/messages/env/weu-prod02/terraform.tfvars
- src/messages/templates/tls-cert.yaml.tpl
- src/payments/02_namespace.tf
- src/payments/99_variables.tf
- src/payments/README.md
- src/payments/env/weu-beta/terraform.tfvars
- src/payments/env/weu-prod01/terraform.tfvars
- src/payments/env/weu-prod02/terraform.tfvars
- src/payments/templates/tls-cert.yaml.tpl
- src/profile/02_namespace.tf
- src/profile/99_variables.tf
- src/profile/README.md
- src/profile/env/weu-beta/terraform.tfvars
- src/profile/env/weu-prod01/terraform.tfvars
- src/profile/env/weu-prod02/terraform.tfvars
- src/profile/templates/tls-cert.yaml.tpl
- remove tls storage account
- add azurite sidecar
tls check is based on azure function sdk with a timer triggered function that needs an azure storage to run.
We simplified tls check using azurite instead a real storage account.
---
> Add azurite into tls check

- src/.template/02_namespace.tf
- src/aks/01_monitor.tf
- src/aks/03_monitoring.tf
- src/aks/99_variables.tf
- src/aks/README.md
- src/aks/env/weu-beta/terraform.tfvars
- src/aks/env/weu-prod01/terraform.tfvars
- src/aks/env/weu-prod02/terraform.tfvars
- src/aks/templates/tls-cert.yaml.tpl
- src/messages/02_namespace.tf
- src/payments/02_namespace.tf
- src/profile/02_namespace.tf
- add tls check for apim endpoints
like https://github.com/pagopa/io-infra/pull/217 but with apim internal endpoints
---
> Add tls check for apim endpoints

- src/.template/01_monitor.tf
- src/.template/02_namespace.tf
- src/.template/99_variables.tf
- src/.template/README.md
- src/.template/env/weu-beta/terraform.tfvars
- src/.template/env/weu-prod01/terraform.tfvars
- src/.template/env/weu-prod02/terraform.tfvars
- src/aks/03_monitoring.tf
- src/aks/README.md
- src/messages/01_monitor.tf
- src/messages/02_namespace.tf
- src/messages/99_variables.tf
- src/messages/README.md
- src/messages/env/weu-beta/terraform.tfvars
- src/messages/env/weu-prod01/terraform.tfvars
- src/messages/env/weu-prod02/terraform.tfvars
- src/payments/01_monitor.tf
- src/payments/02_namespace.tf
- src/payments/99_variables.tf
- src/payments/README.md
- src/payments/env/weu-beta/terraform.tfvars
- src/payments/env/weu-prod01/terraform.tfvars
- src/payments/env/weu-prod02/terraform.tfvars
- src/profile/01_monitor.tf
- src/profile/02_namespace.tf
- src/profile/99_variables.tf
- src/profile/README.md
- src/profile/env/weu-beta/terraform.tfvars
- src/profile/env/weu-prod01/terraform.tfvars
- src/profile/env/weu-prod02/terraform.tfvars
- add alerts for tls check
Alerts for internal tls certs
---
> Add alerts for tls check certs

- src/aks/scripts/setup.sh
> Refactor AKS setup script

- .devops/messages-code-review-pipelines.yml
- .devops/messages-deploy-pipelines.yml
- .devops/payments-code-review-pipelines.yml
- .devops/payments-deploy-pipelines.yml
- .devops/profile-code-review-pipelines.yml
- .devops/profile-deploy-pipelines.yml
- src/domains/profile-app/03_serviceaccounts_azure_devops.tf
- src/domains/profile-app/README.md
- src/domains/profile-common/02_key_vault.tf
- src/domains/profile-common/README.md
- added profile pipelines for code-review and deploy
- added kv permissions for iac sp
- added service account system 
Allow profile domain to have its own pipelines
---
> feat: added profiles pipelines for domains

- .devops/sign-code-review-pipelines.yml
- .devops/sign-deploy-pipelines.yml
- src/core/README.md
- src/core/selfcare.tf
- src/domains/sign/README.md
- src/domains/sign/key_vault.tf
Add io-sign cicd
depends on https://github.com/pagopa/io-azure-devops/pull/11
---
> Add cicd sign

- src/domains/sign/README.md
- src/domains/sign/io_sign_func.tf
1. add `IOApiSubscriptionKey` env var
2. update the value of `CosmosDbConnectionString` var
---
> fix: update env var for io-sign-func

- src/domains/sign/api/issuer/v1/_openapi.yaml
I updated the io-sign openapi specification, adding a missing endpoint
---
> update openapi spec

- src/domains/sign/README.md
- src/domains/sign/storage.tf
Add a new container called "documents" into "iosignst" blob storage
---
> Add "documents" container to "iosignst" blob storage

- src/domains/sign/io_sign_func.tf
Add new queues to io-sign internal storage.
> Add queue to internal "iosign" blob storage

- src/domains/sign/README.md
- src/domains/sign/data.tf
- src/domains/sign/io_sign_func.tf
- src/domains/sign/network.tf
> fix io-sign internal storage

- src/core/README.md
- src/core/private_dns_zones.tf
- src/domains/messages-common/README.md
- Add cosmos private link to vnet beta, 01 and 02
AKS needs to resolve cosmos private ip addresses
---
> Add cosmos private link to vnet beta, 01 and 02

- src/core/README.md
- src/core/private_dns_zones.tf
Add storage account private link to vnet beta, 01 and 02
AKS needs to resolve storage account private ip addresses
---
> Add private link storage account to vnet 01,02 and beta

- src/domains/messages-app/04_storage.tf
- src/domains/messages-common/03_database.tf
- src/domains/messages-common/04_storage.tf
> [#ICC-205] Add messages KV secrets

- src/core/app_backend.tf
see commit list
This is the remediation for the upcoming failures occurring in the login process. SAML assertions fail to validate their dates as they are considered future dates. 
We found we can loosen this constraint a bit by tolerating 5s instead of 2s, without compromising our vulnerability to malicious behavior.
---
> [#/IOCIT-120] Set accepted clock skew to 5000

- src/core/.terraform.lock.hcl
- src/core/data.tf
- src/core/function_messages_cqrs.tf
- src/domains/messages-app/env/weu-prod01/terraform.tfvars
- src/domains/messages-common/01_network.tf
- src/domains/messages-common/03_database.tf
- src/domains/messages-common/06_events.tf
- src/domains/payments-app/env/weu-prod01/terraform.tfvars
- src/domains/payments-common/04_events.tf
- Add new resources for Reminder 
- Modify EVH topic names
This is required by reminder component
---
> [#ICC-211] Configure Reminder resources

- src/domains/messages-common/05_apim.tf
> [#ICC-233] add new groups `ApiReminderNotify` and `ApiNewMessageNotify`

- src/core/README.md
- src/core/app_backend.tf
- src/domains/messages-common/README.md
- src/domains/payments-common/README.md
Update `IDP_METADATA_URL` and `CIE_METADATA_URL` to retrieve metadata from Eng Identity Service.
We are using a static copy for SPID metadata that needs to be manually updated. The new Engineering Identity Services provide a new endpoint that cache the metadata from AgID and IPZS.
---
> [#IOCIT-121] Eng Identity Services to get SPID/CIE metadata

- src/core/99_locals.tf
- src/core/app_backend.tf
> Add AKS Outbound IPS to App Backend LI

- src/core/99_locals.tf
- src/core/function_messages_cqrs.tf
- Add Brokers for `io-p-evh-ns`
- Add local definition
This is required by [this PR](https://github.com/pagopa/io-functions-messages-cqrs/pull/15)
---
> [#ICC-245] Add env variables for CQRS EVH

- src/domains/messages-common/05_apim.tf
- src/domains/messages-common/README.md
Add Reminder user to APIM
This is required by reminder component in order to inject subscription key on shared Key Vault 
---
> [#ICC-211] Add Reminder APIM User

- src/domains/messages-common/05_apim.tf
> [#ICC-211] Activate reminder subscription

- src/domains/payments-common/03_database.tf
> [#ICC-211] Remove unique constraints on payment-updater MongoDB

- src/domains/messages-common/api/service-messages/v1/_base_policy.xml
- indent file in [268d83f](https://github.com/pagopa/io-infra/pull/254/commits/268d83f87992e23fef1ebfff8ef30f56460e9cdb)
- add `x-user-group` in [2561c6e](https://github.com/pagopa/io-infra/pull/254/commits/2561c6e8e8be56f36293f501c8e2620c1ac9c9a0)
---
> Fix add policy for fn service messages

- src/domains/payments-common/03_database.tf
- Add mongodb index on `payment` and `payment-retry` collections on field `rptId`
This is needed to avoid 429 from mongo on too high RU consumption while querying entities by `rptId` field.
---
> [#ICC-221] Add index to RptId Field

- src/core/appgateway.tf
Remove apim as backend for api-app.io.pagopa.it and add app-backend
---
> Change api-app.io.pagopa.it backend

- src/core/monitor.tf
change expected http status code for api-app.io.pagopa.it monitor
---
> Fix monitor api-app.io.pagopa.it

- src/core/appgateway.tf
Change app-gateway apim hostname to `api-app.internal.io.pagopa.it`
---
> Change app-gateway apim hostname to `api-app.internal.io.pagopa.it`

- src/core/README.md
- src/core/assets_cdn.tf
> Import old cdn assests.cdn.io.italia.it

- src/core/function_service_cache.tf
Changed functions runtime_version to ~4
We need to upgrade the runtime version for all functions because of v3 end of life.
---
> [#IOCIT-145] Updated functions runtime version in io-functions-services-cache

- src/core/function_service_cache.tf
> [#IOCIT-145] fix added linux_fx_version

- src/core/README.md
- src/domains/messages-app/04_storage.tf
- src/domains/messages-app/env/weu-prod01/terraform.tfvars
- src/domains/messages-common/05_apim.tf
- src/domains/messages-common/06_events.tf
- src/domains/messages-common/README.md
> [#ICC-240]  Fix missing Reminder configuration for eventhub and apim

- src/core/README.md
- src/core/monitor.tf
- added action alert for critical errors
- added 2 news keyvault secrets
Have one channel for critical infos
---
> feat: Added new action alert prod error

- src/core/function_subscription_migrations.tf
> [#IOPAE-112] Enable Application Insights on `fn-subsmigrations`

- src/core/function_devportal_service_data.tf
> Remove Diagnostic Settings Postgresql devportalservicedata

- src/core/function_elt.tf
Add the standard configuration for change feed trigger common lease for services collection.
see commit history
---
> Add config to use the common lease collection for services in fn-elt

- src/domains/messages-common/03_database.tf
> Add Reminder Indexing

- src/core/README.md
- src/core/function_assets_cdn.tf
> Fix linux_fx_version for function_assets_cdn

- src/core/env/prod/terraform.tfvars
> Increase min app gateway instances to 10

- src/core/README.md
- src/core/app_messages.tf
- src/core/env/prod/terraform.tfvars
- src/core/function_assets_cdn.tf
> fix missing linux_fx_version to fn-app-messages

- src/core/app_backend.tf
- src/core/env/prod/terraform.tfvars
- src/core/function_app.tf
- src/core/function_app_async.tf
> [#IOCIT-171] Switch fn-app v4 and app gateway autoscale to min

- src/aks-platform/env/weu-prod01/terraform.tfvars
> Upgrade aks version to 1.23.12

- src/core/99_variables.tf
- src/core/README.md
- src/core/cgn.tf
- src/core/data.tf
- src/core/env/prod/terraform.tfvars
- src/core/function_cgn.tf
- src/core/vpn.tf
* added `function_cgn.tf` file
* edited vars and data
porting of `function_cgn` to io-infra
---
> [#IOCIT-175] Add funtion_cgn

- src/core/README.md
- src/core/data.tf
> removed old fn-app resources

- src/core/99_variables.tf
- src/core/README.md
- src/core/function_cgn.tf
> [#IOCIT-175] edit cgn config

- src/core/env/prod/terraform.tfvars
> Scale up min app gateway to 10

- src/core/function_cgn.tf
> fixed path

- src/core/app_backend.tf
> [#IOCIT-175] updated cgn api url for backends

- src/core/README.md
- src/core/apim_io_backend_v1.tf
- src/core/app_backend.tf
This PR adds the environment variables needed to integrate `io-sign` on `io-backend`.
> [SFEQS-1131] Add env for io-sign backend

- src/core/99_variables.tf
- src/core/README.md
- src/core/env/prod/terraform.tfvars
- src/core/function_eucovidcert.tf
> [#IOCIT-179] Import `fn-eucovidcert` into IAC

- src/domains/sign/cosmos_issuer.tf
I added a new collection on sign's subdomain
We must store the issuers' information data and we can do that using the new issuers collection
> Sfeqs 1157

- src/core/private_dns_zones.tf
- Add privatelink on priovate_dns_zones
This is required in order to add a MySQL instance private link into common VNet
---
> Add MySQL Private link

- src/core/README.md
- src/core/private_dns_zones.tf
- src/domains/messages-common/01_network.tf
- src/domains/messages-common/03_database.tf
- src/domains/messages-common/README.md
> [IOCIT-204] Add MySQL DB

- src/domains/messages-common/03_database.tf
> [#IOCIT-204] Add MySQL Connection config

- src/domains/messages-common/03_database.tf
> [#IOCIT-204] Remove reminder PostgreSQL

- src/core/function_assets_cdn.tf
> [#IOCIT-181 BIS] applied v4 to prod

- src/core/README.md
- src/core/private_dns_zones.tf
* private dns zone
* virtual network link
So that appservice and functionapp can have private endpoint
- [] DEV
> Add privatelink for azurewebsites

- src/core/apim_io_services_api.tf
- src/core/app_messages.tf
- src/core/function_app.tf
- src/core/function_app_async.tf
- src/core/function_assets_cdn.tf
- src/core/function_devportal_service_data.tf
- src/core/function_elt.tf
- src/core/function_messages_cqrs.tf
- src/core/function_publiceventdispatcher.tf
- src/core/function_service_cache.tf
- src/core/function_services.tf
- src/core/function_subscription_migrations.tf
> Remove not used operation for submit message api and fix health check paths

- src/core/app_backend.tf
> App backend allow connections from services

- src/core/api/io_services/v1/policy.xml
- src/core/api_product/io_services/_base_policy.xml
> Change services policy

- src/core/README.md
- src/core/function_services.tf
> [#IOCIT-174] Add Container Name and queues for Fn-Services

- src/core/.terraform.lock.hcl
- src/core/99_main.tf
- src/core/README.md
- src/core/data.tf
- src/core/function_services.tf
> Fix new fn-services (downgrade azurerm to 2.98.0)

- src/domains/sign/storage.tf
Add storage queue to `io-sign` domain
1. `on-signature-request-ready`
2. `on-signature-request-wait-for-signature`
---
3. select PR branch
4. wait for approval
> SFEQS-1205 Add storage queue to sync the Signature Request statuses

- src/core/README.md
- src/core/cgn.tf
> [#IOCIT-183] added apim values for cgn merchant

- src/core/README.md
- src/core/cgn.tf
- src/core/function_services.tf
> Tuning services and app gateway scale out

- src/core/README.md
- src/core/function_public.tf
This PR highly depends on #316  
* reinstated fn-public file
---
> [#IOCIT-182] reinstate fn public file

- src/core/99_variables.tf
- src/core/README.md
- src/core/env/prod/terraform.tfvars
- src/core/network.tf
> Enable DDoS protection

- src/core/README.md
- src/core/app_messages.tf
This is Step 1 for upgrading `fn-app-messages` to v4
- Upgrade staging slot to v4
Upgrade function runtime to v4
---
> [#IOCIT-188] `fn-app-messages` upgrade staging slot to v4 - STEP 1

- src/core/README.md
- src/core/app_messages.tf
This PR depends on https://github.com/pagopa/io-infra/pull/349
This PR depends on https://github.com/pagopa/io-functions-app-messages/pull/31
This PR depends on https://github.com/pagopa/io-infra/pull/353
- Upgrade main slot to v4
- Upgrade `function_app`  module to v3.8.1, that introduce healthcheck alert
- Add `domain` and `action` variables
Upgrade function runtime to v4
---
> [#IOCIT-188] `fn-app-messages` upgrade staging slot to v4 - STEP 2

- src/domains/sign/storage.tf
Adding a queue into an existing storage account
> chore(io-sign): Add missing waiting-for-qtsp queue

- src/core/README.md
- src/core/app_messages.tf
- src/core/function_elt.tf
- src/core/function_public.tf
see commit list
Upgrade function-elt runtime to v4 (due to end-of-life)
---
> [#IOCIT-190] Upgrade function-elt runtime version to v4

- src/core/function_elt.tf
see commit list
Re-enable the analytics functions on function elt after the runtime upgrade
---
> [#IOCIT-190] Enable analytics functions for pdnd on function_elt

- src/core/function_messages_cqrs.tf
- Enable triggers on production slot
---
> [#IOCIT-184] - Functions Messages CQRS migration to V4 Runtime Part 3

- src/core/README.md
- src/core/app_backend.tf
- src/core/data.tf
- Add throttling alert for io-p-cosmos-api
---
> [IOCIT-216] Add `io-p-cosmos-api` throttling alert

- src/core/function_devportal_service_data.tf
* Add connection string to `iopcdnassets` storage
* Add blob path as env variables
* Add Service exclusion list to override service quality measurement
`io-p-devportal-srvdata` will build and store a read model of latest visible service on asset storage, for the website to consume it
---
2. select the PR branch
> [#IOPSC-124] Connect to assets storage

- src/domains/sign/io_sign_issuer_func.tf
- src/domains/sign/io_sign_user_func.tf
- src/domains/sign/storage.tf
The `waiting-message` queue is not used
Depends on https://github.com/pagopa/io-infra/pull/348
---
> chore(io-sign): [SFEQS-1263] Remove unused queue

- src/core/env/prod/terraform.tfvars
- src/domains/messages-app/07_function_pushnotif.tf
see commit history
Add internal connection string to function push-notif staging slot
---
> [IOCIT-177] Add internal connection string to push_notif staging slot

- src/core/function_devportal_service_data.tf
> use prod file names

- src/core/README.md
- src/core/function_public.tf
> Fixes to fn public

- src/domains/messages-app/07_function_pushnotif.tf
- src/domains/messages-app/09_keyvault.tf
- src/domains/messages-app/README.md
> [#IOCIT-177] Add secret for NH endpoints on PushNotif

- src/domains/messages-app/07_function_pushnotif.tf
- src/domains/messages-common/04_storage.tf
- src/domains/messages-common/README.md
> [#IOCIT-177] Add new push notification secret for service messages

- src/core/README.md
- src/core/selfcare.tf
> Updated version jwt_keys for Selfcare

- src/core/function_admin.tf
> fixed SESSION_URL

- src/core/app_backend.tf
Use start script defined in package.json
---
> update app_command_line with npm run start

- src/core/function_messages_cqrs.tf
* Add LEASE_COLLECTION_PREFIX for messages-cqrs; 
---
> Add LEASE_COLLECTION_PREFIX for messages-cqrs

- src/core/app_backend.tf
> [#ICC-273] Fix LolliPOP allowed user agents with patch

- src/core/function_messages_cqrs.tf
> Disable CosmosApiChangeFeedForMessageRetention function

- src/core/apim_io_admin_api.tf
- src/core/function_admin.tf
* Modified apim url 
* Activated UserDataProcessingTrigger
---
> Switch from old fn3-admin to admin-fn running on V4 runtime

- src/core/app_backend.tf
- Update Regex to match up to 30% of users, by allowing 5 characters over 16 ( 5/16 % = ~31% )
Progressive rollout of new pushnotif
---
> Open traffic to new pushnotif function up to 30% of users

- src/core/README.md
- src/core/data.tf
> [Alert monitoring] Added new alert for CGN cosmos db throttling

- src/core/function_messages_cqrs.tf
> Disable CosmosApiMessagesChangeFeed on CQRS

- src/core/api/io_services/v1/post_submitmessageforuserwithfiscalcodeinbody_policy/policy.xml
> fix: Enable routing to old fn-services

- src/core/function_messages_cqrs.tf
> [#ICC-289] - Set MESSAGE_CHANGE_FEED_START_TIME as timestamp

- src/core/app_backend.tf
> Open Prod traffic to new pushnotif function V4

- src/core/selfcare.tf
added permission to send messages when logging in selfcare
changed the permission apilimitedmessagewrite to apimessagewrite
user in selfcare already have a validated contract so we can give them non limited permission
---
N/A
> [#IOPAE-95] added permission to send messages when logging to selfcare

- src/core/99_variables.tf
- src/core/README.md
- src/core/app_backend.tf
- src/core/service.tf
Create an alert on service availability
Observe the quality of service about party integration
---
> [#IOPAE-89] Create alert on sevice availability in quarantine

- src/.template/env/weu-beta/terraform.tfvars
- src/.template/env/weu-prod01/terraform.tfvars
- src/.template/env/weu-prod02/terraform.tfvars
- src/.template/templates/tls-cert.yaml.tpl
- src/aks-platform/env/weu-beta/terraform.tfvars
- src/aks-platform/env/weu-prod01/terraform.tfvars
- src/aks-platform/env/weu-prod02/terraform.tfvars
- src/aks-platform/templates/tls-cert.yaml.tpl
- src/domains/messages-app/env/weu-beta/terraform.tfvars
- src/domains/messages-app/env/weu-prod01/terraform.tfvars
- src/domains/messages-app/env/weu-prod02/terraform.tfvars
- src/domains/messages-app/templates/tls-cert.yaml.tpl
- src/domains/payments-app/env/weu-beta/terraform.tfvars
- src/domains/payments-app/env/weu-prod01/terraform.tfvars
- src/domains/payments-app/env/weu-prod02/terraform.tfvars
- src/domains/payments-app/templates/tls-cert.yaml.tpl
- src/domains/profile-app/env/weu-beta/terraform.tfvars
- src/domains/profile-app/env/weu-prod01/terraform.tfvars
- src/domains/profile-app/env/weu-prod02/terraform.tfvars
- src/domains/profile-app/templates/tls-cert.yaml.tpl
I don't have the permissions to test this PR on the IO cluster
---
> feat: Upgrade version of TLS cert check application

- src/domains/profile-app/.terraform.lock.hcl
- src/domains/profile-app/02_namespace.tf
- src/domains/profile-app/99_locals.tf
- src/domains/profile-app/99_main.tf
- src/domains/profile-app/README.md
- src/domains/profile-app/terraform.sh
- src/domains/profile-common/.terraform.lock.hcl
- src/domains/profile-common/02_key_vault.tf
- src/domains/profile-common/99_locals.tf
- src/domains/profile-common/99_main.tf
- src/domains/profile-common/README.md
- src/domains/profile-common/terraform.sh
> feat: Migrate profile domain to azurerm v3

- src/domains/messages-app/.terraform.lock.hcl
- src/domains/messages-app/02_namespace.tf
- src/domains/messages-app/04_storage.tf
- src/domains/messages-app/06_events.tf
- src/domains/messages-app/07_function_pushnotif.tf
- src/domains/messages-app/99_locals.tf
- src/domains/messages-app/99_main.tf
- src/domains/messages-app/README.md
- src/domains/messages-app/terraform.sh
- src/domains/messages-common/.terraform.lock.hcl
- src/domains/messages-common/02_key_vault.tf
- src/domains/messages-common/03_database.tf
- src/domains/messages-common/04_storage.tf
- src/domains/messages-common/05_apim.tf
- src/domains/messages-common/99_locals.tf
- src/domains/messages-common/99_main.tf
- src/domains/messages-common/README.md
- src/domains/messages-common/terraform.sh
> feat: Upgrade message domain to azurerm v3

- src/core/README.md
- src/core/app_backend.tf
- src/core/data.tf
> fix: Remove old fn3 admin

- src/core/99_variables.tf
- src/core/README.md
- src/core/app_backend.tf
- src/core/env/prod/terraform.tfvars
- Add TP Mock configuration
---
> [#ICC-317] Add TP Mock configuration

- src/core/function_services.tf
Remove auto-heal as suggested by azure advisor
---
> fix: Remove auto-heal fnservices

- src/domains/sign/storage.tf
> io-sign [SFEQS-1322] Add new queues to sync signature request state

- src/aks-platform/.terraform.lock.hcl
- src/aks-platform/01_network.tf
- src/aks-platform/02_aks.tf
- src/aks-platform/03_keda.tf
- src/aks-platform/99_locals.tf
- src/aks-platform/99_main.tf
- src/aks-platform/README.md
- src/aks-platform/terraform.sh
> feat: Upgrade aks-platform to azurerm v3

- src/domains/payments-app/.terraform.lock.hcl
- src/domains/payments-app/02_namespace.tf
- src/domains/payments-app/04_events.tf
- src/domains/payments-app/99_locals.tf
- src/domains/payments-app/99_main.tf
- src/domains/payments-app/README.md
- src/domains/payments-common/.terraform.lock.hcl
- src/domains/payments-common/02_key_vault.tf
- src/domains/payments-common/03_database.tf
- src/domains/payments-common/05_api.tf
- src/domains/payments-common/99_main.tf
- src/domains/payments-common/README.md
> feat: Upgrade payments domain to azurerm v3

- src/core/function_eucovidcert.tf
set urls
Connect `fn-eucovidcert` to `fn-services` instances
---
> [#IOPAE-98] Connect `fn-eucovidcert` to `fn-services` instances

- src/core/README.md
- src/core/api/io_services/v1/post_submitmessageforuserwithfiscalcodeinbody_policy/policy.xml
- src/core/apim_io_services_api.tf
See commit list
After tests proposed in https://github.com/pagopa/io-infra/pull/342, we can now definitely move all the traffic to `fn-eucovidcert`
---
> [#OPAE-98] 100% rollout on new `fn-eucovidcert`

- src/core/99_variables.tf
- src/core/README.md
- src/core/app_messages.tf
- src/core/cgn.tf
- src/core/data.tf
- src/core/env/prod/terraform.tfvars
- src/core/function_admin.tf
- src/core/function_app.tf
- src/core/function_app_async.tf
- src/core/function_cgn.tf
- src/core/function_devportal_service_data.tf
- src/core/function_elt.tf
- src/core/function_messages_cqrs.tf
- src/core/function_public.tf
- src/core/function_services.tf
- src/core/function_subscription_migrations.tf
- src/core/network.tf
The `pendpoints` subnet is defined as a proper resource instead of being referenced as data.
Refactor infrastructure as code belonging to old repos and importing into this stable infra.
- [] DEV
- [] UAT
---
> chore(core): Pendpoints subnet import

- src/core/function_devportal_service_data.tf
- src/core/function_subscription_migrations.tf
See commit list
We misspelled `NODE|14` with `NODE|14-lts` (which is the correct value for node app services).
Additionally, we forced the app to be always on (recommended to avoid cold start issues)
---
> Fix node version

- src/core/api/io_admin/v1/_swagger.json.tpl
Update _IO ADMIN swagger.json.tpl_ with new API `subscriptions/:subscription_id` definition.
- src/core/api/io_admin/v1/_swagger.json.tpl
APIM visibility of new API `subscriptions/:subscription_id`.
---
> [#IOPAE-172] Update io admin swagger tpl

- src/core/99_variables.tf
- src/core/README.md
- src/core/env/prod/terraform.tfvars
- src/core/function_lollipop.tf
Create a new function_lollipop o AppService plan
A new function is required to implement the lollipop flow
---
> [#IOCIT-307] Create new function_lollipop

- src/core/devportal.tf
Dev.Portal: Add manage flow enable user list feature flag
New feature flag `MANAGE_FLOW_ENABLE_USER_LIST` for Manage Flow feature rollout.
---
> [#IOPAE-176] Add manage flow enable user list feature flag

- .github/workflows/prod_cd_citizen-auth.yml
- .github/workflows/prod_ci_citizen-auth.yml
- .github/workflows/prod_drift_citizen-auth.yml
> Fix gh action

- .github/workflows/prod_cd_citizen-auth.yml
- src/domains/citizen-auth-app/env/weu-beta/backend.tfvars
- src/domains/citizen-auth-app/env/weu-prod01/backend.tfvars
- src/domains/citizen-auth-common/env/prod/backend.tfvars
> Move citizen-auth tfstate into new storage account tfinfprodio

- .github/workflows/prod_cd_citizen-auth.yml
- .identity/env/prod/terraform.tfvars
- README.md
> fix IaC roles

- src/.template-app/env/weu-beta/backend.tfvars
- src/.template-app/env/weu-prod01/backend.tfvars
- src/.template-app/env/weu-prod02/backend.tfvars
- src/.template-common/env/prod/backend.tfvars
- src/aks-platform/env/weu-beta/backend.tfvars
- src/aks-platform/env/weu-prod01/backend.tfvars
- src/aks-platform/env/weu-prod02/backend.tfvars
- src/domains/messages-app/env/weu-beta/backend.tfvars
- src/domains/messages-app/env/weu-prod01/backend.tfvars
- src/domains/messages-app/env/weu-prod02/backend.tfvars
- src/domains/messages-common/env/prod/backend.tfvars
- src/domains/payments-app/env/weu-beta/backend.tfvars
- src/domains/payments-app/env/weu-prod01/backend.tfvars
- src/domains/payments-app/env/weu-prod02/backend.tfvars
- src/domains/payments-common/env/prod/backend.tfvars
- src/domains/profile-app/env/weu-beta/backend.tfvars
- src/domains/profile-app/env/weu-prod01/backend.tfvars
- src/domains/profile-app/env/weu-prod02/backend.tfvars
- src/domains/profile-common/env/prod/backend.tfvars
> Move Terraform state to new tfinfprodio storage account

- src/domains/messages-common/03_database.tf
> fix mysql charset

- src/core/README.md
- src/core/app_backend.tf
> [#IOCIT-319] Add Lollipop API env vars to App Backend

- .github/workflows/static_analysis.yml
> Add citizen domain to static_analysis.yml

- src/core/devportal.tf
Added list of (comma separated) APIM userId for whom we want to enable Manage Flow on Service Management.
- src/core/devportal.tf
All users not listed in `MANAGE_FLOW_ENABLE_USER_LIST`, will not be able to get (and also create) the manage subscription.
The "Manage Flow" allows the use of a specific subscription _(Manage Subscription)_ keys as API Key for Service create/update.
**Note:** The list is for the user IDs only, not the full path _APIM.id_.
**First Rollout values:** IDPay, Di Pinto Giuseppe Antonio
---
> [#IOPAE-179] Add first rollout values for MANAGE_FLOW_ENABLE_USER_LIST

- src/domains/citizen-auth-common/api/io_lollipop/v1/policy.xml
> Fix Lollipop API routing

- src/domains/citizen-auth-app/02_security.tf
- src/domains/citizen-auth-app/04_function_lollipop.tf
- src/domains/citizen-auth-app/99_locals.tf
- src/domains/citizen-auth-app/README.md
> [#IOCIT-302]  Add jwt certificate v1

- src/domains/citizen-auth-app/02_security.tf
- src/domains/citizen-auth-app/README.md
- src/domains/citizen-auth-common/02_key_vault.tf
- src/domains/citizen-auth-common/99_locals.tf
- src/domains/citizen-auth-common/README.md
move certificate generation to common
---
> fix: [#IOCIT-302] move certificate to common

- src/domains/citizen-auth-common/02_key_vault.tf
> [#IOCIT-302] add `CreateCertificate` permission to cd pipeline

- src/domains/citizen-auth-app/04_function_lollipop.tf
> Fix exported certificates to env variables

- src/core/README.md
- src/core/cgn.tf
> Remove old CGN fn3 subnet

- src/domains/citizen-auth-app/04_function_lollipop.tf
> Fix Cosmos DB Name on FN Lollipop

- src/core/README.md
- src/core/function_services.tf
- io-infra/src/core/function_services.tf
Add new cosmos subscription-cidrs container to store APIM Subscription authorized CIDRs
---
> [#IOPAE-199] Add subscription-cidrs Cosmos container

- src/domains/sign/99_variables.tf
- src/domains/sign/README.md
- src/domains/sign/cosmos.tf
- src/domains/sign/env/prod/terraform.tfvars
Enable additional geo locations
It was temporarely disabled due to Azure Resouces not available in North EU
Depends on #417 
---
> [SFEQS-1229]: Add secondary region to cosmos

- src/domains/sign/README.md
- src/domains/sign/api_product/sign/_base_policy.xml
- src/domains/sign/apim.tf
- API Product base policy
Change the base policy of the IO-Sign product so that it can validate CIDR ranges other than sigle IPs
Depends on #421
---
> [SFEQS-1228]: Whitelist caller from its CIDR

- src/core/README.md
- src/core/cgn.tf
- src/core/devportal.tf
- src/core/function_devportal_service_data.tf
- src/core/function_subscription_migrations.tf
- src/core/migrate.sh
- src/core/selfcare.tf
> Migrare App Service backend devportal e selfcare di IO al modulo azurerm v3

- src/domains/citizen-auth-common/01_network.tf
- src/domains/citizen-auth-common/03_storage.tf
- src/domains/citizen-auth-common/README.md
> fix: Add queue private endpoint for lollipop

- src/core/README.md
- src/core/_import_script.sh
- src/core/app_backend.tf
- src/core/cgn.tf
- src/core/env/prod/backend.tfvars
- src/core/function_eucovidcert.tf
- src/core/nat_gateway.tf
imported resources:
- nat gateway
---
> [DEVOPS-939] Import old infra-live-new resources - step3

- src/domains/sign/io_sign_user_func.tf
This PR add `BillingEventHubConnectionString` to `io-func-sign-user`
---
> chore: [SFEQS-1352] Add `BillingEventHubConnectionString` to `io-func-sign-user`

- src/domains/citizen-auth-app/04_function_lollipop.tf
> Fix lollipop unwanted changes

- src/core/function_services.tf
rollback changes from https://github.com/pagopa/io-infra/pull/412
---
> Remove app-backend from aks step1 (point to app-backendli)

- src/domains/sign/api_product/sign/_base_policy.xml
- src/domains/sign/apim.tf
- src/domains/sign/cosmos_issuer.tf
Rename issuers whitelist collection name (remove IP) to support also CF whitelist.
Depends on #503 
---
> chore: [SFEQS-1543] Rename whitelist collection

- src/domains/sign/apim.tf
- Remove` io-sign-cosmosdb-issuer-whitelist-ip-collection-name` APIM named value
- Remove` io-sign-ip-validated` APIM named value
---
> chore: Remove unused resources for `io-sign`

- src/domains/sign/network.tf
Import the already existing NAT Gateway and attach to the subnets
The functions need to communicate towards the outside world through the NAT Gateway
⚠️ Please use the `terraform import` command to update the state with the already existing resources
---
> feat(sign): Use NAT Gateway

- src/domains/sign/README.md
- src/domains/sign/io_sign_issuer_func.tf
- src/domains/sign/io_sign_user_func.tf
Migrate function_app `io_sign_issuer_func` to terraform provider v3
Migrate function_app `io_sign_issuer_func_staging_slot` to terraform provider v3
Migrate function_app `io_sign_user_func` to terraform provider v3
Migrate function_app `io_sign_user_func_staging_slot` to terraform provider v3
Resources currently used, are soon to be deprecate in further versions of the terraform provider
---
1. terraform import $new_resource_name $function_app_id
2. terraform state rm "$old_resource_name"
> chore(sign): [SFEQS-1522] Migrazione azure functions a v3

- src/core/function_services.tf
add FF config var to fn-services
The message notification via email will now use a html generated form a markdown template. This template will enanche the client compatibility and ease further changes.
---
> [#ICC-293] Add FF for message email template to fn-services

- src/domains/citizen-auth-common/01_monitor.tf
- src/domains/citizen-auth-common/05_database.tf
- src/domains/citizen-auth-common/README.md
-  Add NormalizedRUConsumption exceeded alert
Opex
---
> [#IOCIT-380] Add NormalizedRUConsumption exceeded alert

- src/domains/citizen-auth-common/05_database.tf
See commit history
Fix apply
---
> [#IOCIT-380] fix aggregation criteria

- src/core/app_messages.tf
> Update node version for app messages staging slot

- src/domains/messages-app/07_function_pushnotif.tf
> Update node to 18 pushnotif staging

- src/domains/messages-app/07_function_pushnotif.tf
> Update node to 18 for prod pushnotif

- src/domains/citizen-auth-common/05_database.tf
- src/domains/citizen-auth-common/99_variables.tf
- src/domains/citizen-auth-common/README.md
- src/domains/citizen-auth-common/env/prod/terraform.tfvars
- Add location_full variable
- Fix alert scope
---
> [#IOCIT-380] add location_full, try fix alert rule

- src/core/99_variables.tf
- src/core/README.md
- src/core/env/prod/terraform.tfvars
- src/core/redis.tf
Upgrade redis module to `v6.3.0`
Set redis_version to 6
---
> [#IOPID-111] Upgrade redis module to `v6.3.0` and set redis_version to 6

- src/domains/sign/io_sign_issuer_func.tf
- src/domains/sign/io_sign_support_func.tf
- src/domains/sign/io_sign_user_func.tf
- src/domains/sign/key_vault.tf
- src/domains/sign/network.tf
Add private endpoints also for functionapp slots
Allow private networking also for stages
---
> feat(sign): Add function slots to private endpoints

- src/core/function_public.tf
* [Update node version for fn-public staging slot](https://github.com/pagopa/io-infra/commit/949c1b1d513e7ac4d109626e687dab52431bcbfa);
End of life Node 14
---
> [ICC-353] Update node version for fn-public staging slot

- src/core/function_public.tf
> [IOCOM-11] Update Node to 18 for fn-public prod

- src/core/function_admin.tf
> [IOCOM-97] Update node for fn admin staging slot

- src/core/function_admin.tf
> Revert "Revert "[#IOCOM-97] Update Node to 18 for fn-admin prod""

- src/core/function_services.tf
* Update node to 18 for fn-services prod
---
> [#IOCOM-94] Update linux_fx_version for fn services prod

- src/core/function_elt.tf
> [#IOCOM-13] update node 18 function elt

- src/core/function_elt.tf
> [#IOCOM-13] update node18 fn elt

- src/core/99_variables.tf
- src/core/README.md
- src/core/appgateway.tf
- src/core/continua_dynamiclink.tf
- src/core/env/prod/terraform.tfvars
- src/core/monitor.tf
- Configure app gateway for continua.io.pagopa.it (listener, backend, probe, certificate)
- Define appservice for continua dynamiclink
- Define TLS monitoring
Define a service to resolve dynamiclink to mobile app or appstore via QR code
Depends on pagopa/gitops#343
---
> feat(continua): [SFEQS-1597] Setup the infrastructure for QR code dynamic link

- src/core/function_app_async.tf
* [Update linux_fx_version](https://github.com/pagopa/io-infra/commit/728076730006f96cba53536668e8ed3d7e2f451f);
---
> Update linux_fx_version fn-app-async staging slot

- src/core/function_app.tf
- src/core/function_app_async.tf
* [Update linux_fx_version for fn app prod](https://github.com/pagopa/io-infra/commit/2d8e6f44d7c36b68d0a9ca8bd008d80ec712b906);
End of life node 14
---
> Update linux_fx_version for fn app prod

- .github/workflows/prod_cd_citizen-auth.yml
- .github/workflows/prod_ci_citizen-auth.yml
- .github/workflows/prod_drift_citizen-auth.yml
> [#IOPID-106] upgrade runner image tag

- .github/workflows/prod_cd_citizen-auth.yml
- .github/workflows/prod_ci_citizen-auth.yml
- .github/workflows/prod_drift_citizen-auth.yml
> [#IOPID-106] Fix runner tag

- src/core/app_backend.tf
Update node version for backend on staging slot
End of life Node 14
---
> Update node 18 on staging

- src/core/appgateway.tf
- src/core/continua_dynamiclink.tf
- AppService application settings
Provider proper configuration for the service
---
> fix(continua) [SFEQS-1597]: Define AppService configuration environment variables

- src/domains/sign/env/prod/terraform.tfvars
Add allow rules for additional IPs relative to PDND
PDND has multiple endpoints
- [ x Update configuration to existing resources
---
> fix(sign): Allow additional IP addresses towards PDND

- src/core/env/prod/terraform.tfvars
Add new allowed ip for PDND
---
> Add new allowed ip for PDND

- src/core/continua_dynamiclink.tf
Change mobile stores references to production IO App
Update the production configuration
---
> fix(continua): [SFEQS-1628] Production configuration for IO App

- src/domains/sign/io_sign_user_func.tf
> chore: Add IoLinkBaseUrl to io-func-sign-user

- src/core/99_variables.tf
- src/core/README.md
- src/core/app_backend.tf
- src/core/env/prod/terraform.tfvars
> change PN routing

- src/core/app_backend.tf
> Disable alert for appbackend

- src/core/function_cgn.tf
* [src/core/function_cgn.tf](https://github.com/pagopa/io-infra/compare/IOCOM-218-update-fn-cgn-prod-node18?expand=1#diff-7805e9b7a2ad0462ee730bfd681daeb9db71aaf117944ff86a3c1f6675187997);
---
> Update node to 18 for prod

- src/core/function_cgn_merchant.tf
* [Update node version for cgn merchant in staging slot](https://github.com/pagopa/io-infra/commit/4225cb16671e5c73c9af4e42c75e39260009bbe1);
End of life Node 14
---
> [ICC-350] Update node version for cgn merchant in staging slot

- src/core/function_cgn_merchant.tf
*  [Update node to 18 in prod slot](https://github.com/pagopa/io-infra/commit/d94ddafb750f83fe1af615adc98adf1ccdc20537);
---
> [#IOCOM-219] Update node to 18 in prod slot

- src/core/README.md
- src/core/app_backend.tf
Create two new secret in common keyvault.
Some variable are needed by the AKS service, to read the value we move this values from modules into Keyvault secrets.
---
> Add value into storage for AKS use

- src/core/function_services.tf
rollback changes from https://github.com/pagopa/io-infra/pull/496
---
> Revert "Remove app-backend from aks step1 (point to app-backendli)"

- src/domains/sign/storage.tf
> [SFEQS-1575] Added waiting-for-signature-request-updates queue

- src/domains/sign/io_sign_user_func.tf
> [SFEQS-1575] Added UpdateSignatureRequest inside staging_disabled

- src/domains/sign/99_variables.tf
- src/domains/sign/dns.tf
- src/domains/sign/env/prod/terraform.tfvars
Define a DNS zone for the sign domain
Mailup and SES validation tools
---
> feat(sign) [SFEQS-1675]: Define domain specific dns zone

- src/domains/sign/dns.tf
- src/domains/sign/env/prod/terraform.tfvars
Add DNS records for incoming validation
Validate mailup configuration sender
---
> feat(sign): [SFEQS-1674] Add incoming mx to dns zone

- src/core/app_backend.tf
- add `BACKEND_HOST`
- add `IOLOGIN_CANARY_USERS_REGEX`
---
> [#IOPID-202] Add new login redirect absolute paths + canary regex

- src/domains/sign/monitoring.tf
- Adding dedicated monitoring action groups
- Using dedicated action groups in addition to shared ones
Allow the team to quickly identify the relevant alarms
Separation of duties on alarm reaction
---
> feat(sign): [SFEQS-1627] Monitoring alarms on dedicated channel

- src/core/function_services.tf
set email FF to ALL for fn-services
Promote the use of the new email template for messages from BETA users to ALL citizens
---
> [#] Open new email template for messages to all

- src/core/function_app.tf
set email FF to ALL for fn-app
Promote the use of the new email template for email validation from BETA users to ALL citizens
---
> [#] Open new email template for email validation to all

- src/core/function_services.tf
> fix: Point to appbackendli

- src/domains/citizen-auth-common/03_apim.tf
- src/domains/citizen-auth-common/README.md
* see commit history
added new subscription key that will be used in fast-login azure functions
---
> [#IOPID-329] add functions-fast-login subscription-key

- src/core/app_backend.tf
> disabled lollipop for io sign third party endpoints

- src/core/README.md
- src/core/app_backend.tf
- See commit
Add new variable for enabling LV beta testing
---
> [#IOPID-257] Add new variable for LV beta testing

- src/core/api/cgn/v1/_base_policy.xml
- src/core/api/cgn/v1/_swagger.json.tpl
- src/core/function_cgn_merchant.tf
> [#PE-357] Swapped cgn merchant path to be coherent with documentation

- src/domains/citizen-auth-common/01_network.tf
- src/domains/citizen-auth-common/05_database.tf
- src/domains/citizen-auth-common/README.md
io-openid-provider will need a mongo db.
---
> [#IOCOM-309] Added CosmosDB with Mongo API for OpenID Provider

- src/core/function_messages_cqrs.tf
This PR is required n order to reactivate `CosmosApiMessagesChangeFeed` trigger
---
> Reactivate CQRS trigger for Messages

- src/domains/citizen-auth-app/04_fims.tf
> [#IOCOM-309] fix fims infra variables

- src/domains/citizen-auth-app/04_fims.tf
- src/domains/citizen-auth-common/02_key_vault.tf
> Add port and jwkprimarykey

- src/core/function_services.tf
[Add PN_SERVICE_ID to fn_services, also set feature flag to canary](https://github.com/pagopa/io-infra/commit/15ba835f3f9d1bf473b1627ac1ed267d59e6e087)
---
> [#IOCOM-332] Add PN_SERVICE_ID to fn_services, also set feature flag to canary

- src/core/README.md
- src/domains/citizen-auth-app/07_function_fast_login.tf
- src/domains/citizen-auth-app/README.md
Rename LolliPoP ENVs var name in `fn-fast-login`
Regenerate the docs that contains unexpected changes.
The variables needed to configure the `fn-lollipop` client has a misunderstandable `LC` prefix.
---
> Rename LolliPoP ENVs in fn-fast-login

- src/domains/citizen-auth-app/04_fims.tf
> Fix variables for fims

- src/core/app_backend.tf
> [#IOCOM-355] removed real cf in PN testUser

- src/core/README.md
- src/core/app_backend.tf
- Add `app_backend_FAST_LOGIN_API_KEY` (data)
- Add `FAST_LOGIN_API_KEY` and `FAST_LOGIN_API_URL` to appbackend env variables
---
> [#IOPID-269] Add fast-login Url and Api Key to appbackend

- src/core/99_locals.tf
- src/core/api/io_backend/app/v1/_swagger_v2.json.tpl
- src/core/apim_v2.tf
- src/core/apim_v2_io_backend_v1.tf
> Activate Apim v2 hostname config

- src/core/README.md
- src/core/app_backend.tf
- Remove unused `app_backend_PN_API_KEY`, `app_backend_PN_API_KEY_UAT` keys
- Add `app_backend_PN_API_KEY_PROD`
- Update PN base path to `https://api-io.notifichedigitali.it`
---
> Remove useless key, upgrade pn variables

- src/core/99_variables.tf
- src/core/README.md
- src/core/azure_devops_agent.tf
- src/core/env/prod/terraform.tfvars
- src/packer/.terraform.lock.hcl
- src/packer/01_azure_devops_agent.tf
- src/packer/99_main.tf
- src/packer/99_main.tf.ci
- src/packer/99_variables.tf
- src/packer/README.md
- src/packer/env/prod/backend.ini
- src/packer/env/prod/backend.tfvars
- src/packer/env/prod/terraform.tfvars
- src/packer/terraform.sh
- deleted old scale set 
- created new scale set infra with ubuntu 22.04
- created packer tools
Upgrade azdo scale sets to use an immutable image with all tools installed
---
> feat: Azdo new scale set infra for io-prod-linux 

- src/domains/citizen-auth-common/03_apim_v2.tf
- src/domains/citizen-auth-common/README.md
- src/domains/messages-common/05_apim_v2.tf
- src/domains/messages-common/README.md
> Fix secrets and add post-migration comments

- src/domains/citizen-auth-app/04_fims.tf
- src/domains/citizen-auth-app/README.md
- src/domains/citizen-auth-common/05_database.tf
- src/domains/citizen-auth-common/README.md
> [#IOCOM-361] Fixed infra for fims

- .devops/core-code-review-pipelines.yml
- src/core/azure_devops_agent.tf
- src/core/monitor.tf
- src/domains/messages-app/02_namespace.tf
- src/domains/payments-app/01_monitor.tf
- src/domains/payments-app/02_namespace.tf
- src/domains/payments-app/README.md
- src/domains/profile-app/01_monitor.tf
- src/domains/profile-app/02_namespace.tf
- src/domains/profile-app/README.md
- remove intesa and etna spid test (manual from azure portal)
- fix continua.io.pagopa.it expected response code (http 302)
- fix alert channel for Availability test
---
> Fix Availability test

- src/domains/citizen-auth-app/04_fims.tf
> [#IOCOM-365] added APPINSIGHTS_SAMPLING_PERCENTAGE to fims locals

- src/domains/citizen-auth-common/05_database.tf
>  [#IOCOM-365] updated fims mongodb version

- src/core/function_app.tf
- src/core/monitor.tf
* added 2 required variables needed for the login email flow to function
those values are intended to be changed after the magic link service has been created. 
however they need to be deployed with dummy values for the MVP.
---
> [#IOPID-384] add required env variables for function_app

- src/domains/citizen-auth-app/04_fims.tf
> [#IOCOM-361] added conf

- src/core/README.md
- src/core/monitor.tf
> Refine Webtest availability frequency alarms

- src/core/README.md
- src/core/app_backend.tf
Setup CIE test env variables
---
> [#IOPID-490] Add variables to setup CIE test env

- src/core/function_app.tf
- [set helpdesk email](https://github.com/pagopa/io-infra/commit/2427f89ee9c25ab37e98de83bb326e6b67d14bf3)
Right now the login email helpdesk link is not defined. Set it to `mailto:beta.loginveloce@pagopa.it` during the beta testing phase.
---
> [#IOPID-501] set helpdesk email

- src/core/README.md
- src/core/dns_ioweb_it.tf
> [#IOPID-558] Add DNS zone for ioapp.it

- src/core/README.md
- src/core/apim_v2_cgn.tf
- src/core/cgn.tf
- src/core/dns_io_italia_it.tf
- src/core/private_dns_zones.tf
- src/core/selfcare.tf
> Reduce dns ttl for apim-v2 migration

- src/core/selfcare.tf
> [#IOPAE-456] Remove duplicated LOCK_SELFCARE_CREATE_NEW_APIM_USER

- src/core/README.md
- src/core/apim_io_services_api.tf
- src/core/apim_v2_io_services_api.tf
> [#IOPAE-456] Remove service activation from mock policy

- src/core/appgateway.tf
1. removed all references to `firmaconio.selfcare` from `appgateway`
---
> Comment references to firmaconio.selfcare from appgateway.tf

- src/core/appgateway.tf
- src/core/dns_firmaconio_selfcare_pagopa_it.tf
- src/core/monitor.tf
1. comment out firmaconio configuration from `appgateway.tf` configuration
the backoffice of firmaconio will exposed on internet through the common app gateway, this config enables it!
---
> [SFEQS-1863/2] Add firmaconio to appgateway

- src/core/README.md
- src/domains/payments-common/03_database.tf
- src/domains/payments-common/README.md
- src/domains/sign/env/prod/terraform.tfvars
Added a new collection for payment with shard_key on rptId.
We need to migrate to sharded collections because of quota limit reached.
---
> [#IOCOM-462] Created new sharded collection for payments

- src/domains/payments-common/03_database.tf
> [#IOCOMO-462] fixed lock

- src/core/selfcare.tf
Add configuration for `request-review-legacy` queue.
- ADD `REQUEST_REVIEW_LEGACY_QUEUE_CONNECTIONSTRING` config on `selfcare.tf`
- ADD `REQUEST_REVIEW_LEGACY_QUEUE_NAME` config on `selfcare.tf`
---
> fix: [#IOPAE-489] Added missing config on selfcare

- src/domains/ioweb-common/02_security.tf
- src/domains/ioweb-common/README.md
- Add azure devops policy policies
---
> fix: [#IOPID-598] Add access policy for CI/CD

- src/domains/citizen-auth-common/03_apim.tf
- src/domains/citizen-auth-common/03_apim_v2.tf
- src/domains/citizen-auth-common/README.md
- src/domains/messages-common/05_apim.tf
- src/domains/messages-common/05_apim_v2.tf
- src/domains/messages-common/README.md
> [#IOPLT-19] Import APIM secrets after APIM v2 restore

- src/core/README.md
- src/core/apim_v2.tf
> [#IOPLT-19] Import PN LC subscription on APIM v2

- src/core/apim_v2_cgn.tf
> service_contributor

- src/core/dns_io_italia_it.tf
- src/core/private_dns_zones.tf
> Switch dns to api management v2

- .github/workflows/ioweb_prod_cd.yml
- .github/workflows/ioweb_prod_ci.yml
- .github/workflows/ioweb_prod_drift.yml
- src/domains/ioweb-app/.terraform.lock.hcl
- src/domains/ioweb-app/00_azuread.tf
- src/domains/ioweb-app/01_monitor.tf
- src/domains/ioweb-app/01_network.tf
- src/domains/ioweb-app/02_security.tf
- src/domains/ioweb-app/05_resource_group.tf
- src/domains/ioweb-app/99_locals.tf
- src/domains/ioweb-app/99_main.tf
- src/domains/ioweb-app/99_variables.tf
- src/domains/ioweb-app/README.md
- src/domains/ioweb-app/env/weu-prod01/backend.ini
- src/domains/ioweb-app/env/weu-prod01/backend.tfvars
- src/domains/ioweb-app/env/weu-prod01/terraform.tfvars
- src/domains/ioweb-app/terraform.sh
This PR depends on https://github.com/pagopa/io-infra/pull/643
- Add `ioweb-app` (env prod01)
Add new `ioweb` domain for making applies quicker and simpler
---
> [#IOPID-598] Add `ioweb-app` domain

- .github/workflows/ioweb_prod_ci.yml
> fix: Github action ci ioweb prod

- .github/workflows/ioweb_prod_cd.yml
- .github/workflows/ioweb_prod_drift.yml
- .github/workflows/prod_cd_citizen-auth.yml
- .github/workflows/prod_ci_citizen-auth.yml
- .github/workflows/prod_drift_citizen-auth.yml
- src/domains/citizen-auth-app/06_storage.tf
- src/domains/citizen-auth-app/07_function_fast_login.tf
- src/domains/citizen-auth-common/03_storage.tf
- src/domains/citizen-auth-common/README.md
Create a new storage with BYOK capability.
The new storage has private endpoint configuration.
Create a container `logs` into the storage.
Add a new env in `fn-fast-login` with the connection string.
The function fast login needs a new storage to save the audit logs for all the token refresh operation.
---
> [#IOPID-279] Create new LV Audit Log storage

- src/domains/ioweb-common/02_security.tf
- src/domains/ioweb-common/README.md
Allow Azure DevOps pipeline to access ioweb kv.
---
> Add azure devops pipeline Read permission to ioweb kv

- src/domains/ioweb-common/06_cdn.tf
* fixed `keyvault_subscription_id` reference on ioweb CDN
---
> fix ioweb cdn subscription id reference

- src/domains/ioweb-common/02_security.tf
- src/domains/ioweb-common/README.md
* added kv access policy for `Microsoft.AzureFrontDoor-Cdn`
---
> add ioweb kv access policy

- src/core/appgateway.tf
Increase Dynamic threshold for Compute Usage of App Gateway from 2 to 3 event in a row.
This warning is triggered too frequently.
---
> [#IOPID-751] Increase dynamic threshold AppGw to 3

- src/core/README.md
- src/core/monitor.tf
Co-authored-by: Davide Marro <drmarro@users.noreply.github.com>
---
> [#IOPLT-158] Map Mailup Alert into Terraform

- src/core/99_variables.tf
- src/core/README.md
- src/core/app_backend.tf
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/function_app.tf
- src/domains/citizen-auth-app/01_network.tf
- src/domains/citizen-auth-app/07_function_fast_login.tf
- src/domains/citizen-auth-app/README.md
- src/domains/ioweb-common/01_network.tf
- src/domains/ioweb-common/10_spid_login.tf
- src/domains/ioweb-common/README.md
This PR depends on #678 for the subnet creation
* added the azure_subnet of `ioweb-profile-fn` in `core`, `ioweb-common` and `citizen-auth-app` domains (functions_app, ioweb hub-spid-login instance and functions_fast_login are all downstream micro-services called by the new azure function)
* added the azure_subnet of `functions_fast_login` in `core` domain(appbackendli will also be a downstream component)
---
> [#IOPID-581] add subnet to downstream components

- src/core/00_github_runner.tf
> change container image

- src/domains/ioweb-app/06_function_ioweb_profile.tf
* added two new required env variables
* align infra with project requirements
---
> update ioweb-profile-backend config with new required env variables

- src/domains/ioweb-app/07_apim_v2.tf
- src/domains/ioweb-app/99_locals.tf
> [IOPID-875] Change backend URI of IO-BFF API group definition

- .github/workflows/gh_runner-scheduler.yml
Update cron expression to match 09AM and 06PM GMT+2 timezone, since GitHub uses UTC.
This pipeline is in charge of increasing and reducing the minimum number of GitHub runner instances in the container app target, in order to avoid cold starts (~30 secs). Although cron expressions were wrong, they had no impact at all - runners are not used yet.
Pipeline was triggered but not at the required time - 11AM GMT+2 and 08PM GMT+2 rather than 09AM and 06PM.
---
> [DevEx-4] Scale scheduler changes

- .github/workflows/gh_runner-scheduler.yml
Update the container app job name
Update the container app job name with the correct one
---
> [DevEx-4] Update job runner name in gh scheduler pipeline

- src/domains/ioweb-common/10_spid_login.tf
- Enable SPID Validator for testing
- Update FE endpoint for final redirects
- [z] Update configuration to existing resources
---
> [#IOPID-949] Enable SPID validator

- src/domains/sign/io_sign_backoffice_func.tf
1. Add `staging` slot to `io-p-sign-backoffice-func`
---
> [io-sign] Add staging slot to io-p-sign-backoffice-func

- src/core/README.md
- src/core/function_app.tf
* [[#IOPID-867] updated env variables](https://github.com/pagopa/io-infra/commit/797f9be24954913b17f46d1f8f832219c88999d2)
update env variables
---
> [#IOPID-867] updated env variables

- src/domains/sign/io_sign_backoffice_func.tf
- src/domains/sign/network.tf
1. Set `/health` as health check path for `io-sign-backoffice-func` and its staging slot
2. Add private endpoint for `io-sign-backoffice-func-staging`
3. Configure access policy to kv for `io-sign-backoffice-func` and its staging slot
---
> chore(sign): Add health check to io-sign-backoffice-func

- src/domains/sign/env/prod/terraform.tfvars
1. Add `SLACK_WEB_HOOK_URL` environment variable to `io-p-sign-backoffice-app` and `io-p-sign-backoffice-func`
2. Add `SELFCARE_API_KEY` to `io-p-sign-backoffice-func`
---
> chore(sign): [SFEQS-2008] Add environment variables

- src/domains/sign/io_sign_backoffice_app.tf
- src/domains/sign/io_sign_issuer_func.tf
- src/domains/sign/storage.tf
1. Add `api-keys` storage queue, to sync Api Key between `backoffice` and `issuer` services
2. Assign `Sender`/`Processor` roles to resources
at the moment `issuer` and `back office` services communicates through rest API, this method makes them extremely coupled with this change we switch to async communication (queue)
---
> add queue and role assignments

- src/domains/citizen-auth-app/01_network.tf
- src/domains/citizen-auth-app/04_redis_common.tf
- src/domains/citizen-auth-app/07_function_fast_login.tf
- src/domains/citizen-auth-app/99_variables.tf
- src/domains/citizen-auth-app/README.md
- src/domains/citizen-auth-app/env/weu-beta/terraform.tfvars
- src/domains/citizen-auth-app/env/weu-prod01/terraform.tfvars
- Add new `cidr_subnet_redis_common` variable (`127.0.0.5/32`)
- Add new subnet
- Add new Redis resource
---
> Add Redis for citizen-auth domain

- src/domains/citizen-auth-app/01_network.tf
- src/domains/citizen-auth-app/07_function_fast_login.tf
- src/domains/citizen-auth-app/99_variables.tf
- src/domains/citizen-auth-app/README.md
- src/domains/citizen-auth-app/env/weu-beta/terraform.tfvars
- src/domains/citizen-auth-app/env/weu-prod01/terraform.tfvars
- src/domains/citizen-auth-common/01_network.tf
- src/domains/citizen-auth-common/04_redis_common.tf
- src/domains/citizen-auth-common/99_variables.tf
- src/domains/citizen-auth-common/README.md
- src/domains/citizen-auth-common/env/prod/terraform.tfvars
- Move redis to citizen-auth-common domain
---
> Move redis to citizen-auth-common domain

- src/domains/citizen-auth-app/04_redis.tf
- src/domains/citizen-auth-app/07_function_fast_login.tf
- src/domains/citizen-auth-app/README.md
- [link newly created redis to fn-fast-login variables](https://github.com/pagopa/io-infra/commit/1472de0a753acdc88a33e6574051574038f2e6cb)
---
> [#IOPID-278] Link newly created redis to fn-fast-login variables

- src/domains/sign/cosmos_issuer.tf
1. Add `issuer-by-subscription-id` collection on `io-p-sign-cosmos`
this collection will act as a lookup table to connect subscription id with issuer data, generated by our backoffice app
--- right now the issuer service gets this data by performing an http call directly to the backoffice, but we want to reduce coupling between these services
---
> feat(sign): Add "issuer-by-subscription-id" collection to issuers db

- src/core/99_variables.tf
- src/core/README.md
- src/core/app_backend.tf
- src/core/env/prod/terraform.tfvars
> [#IOCOM-647] Added config for Remote Content receipt service prod

- src/core/env/prod/terraform.tfvars
> [#IOCOM-647] updated service id

- src/core/99_variables.tf
- src/core/README.md
- src/core/app_backend.tf
- src/core/env/prod/terraform.tfvars
> [#IOCOM-647] splitted test and prod config for receipt service

- src/core/README.md
- src/core/data.tf
- src/core/function_subscription_migrations.tf
Allow `services-cms-backoffice-snet` on `subscription-migration` AZF
---
> [#IOPAE-787]allow services-cms-backoffice subnet in io-subscription-migration

- src/core/app_backend.tf
* [[#IOPID-1109] added backend test_users to LV_TEST_USERS list](https://github.com/pagopa/io-infra/commit/f3f4e6f0d38a22d5a94aba6686446d551d73324e)
abilitate backend TEST_USERS to fast-login
---
> [#IOPID-1109] add backend test_users to LV_TEST_USERS list

- src/domains/messages-common/api/io-backend-notification/v1/_base_policy.xml
- src/domains/messages-common/api/service-messages/v1/_base_policy.xml
- src/domains/payments-common/api/payments_updater/v1/_base_policy.xml
This is required in order to destroy and recreate weu-prod aks cluster.
---
> [#IOPLT-268] Move Production traffic routing through weu-beta

- src/core/app_backend.tf
Add a new ENV variable to `io-backend`.
To enable the clock skew log event a new ENV variable must be set to `true`.
---
> [#IOPID-1145] Enable Clock Skew log event `io-backend`

- src/core/api/io_admin/v1/_swagger.json.tpl
Removed all the references to the master of `io-functions-commons` in favour of the latest tag
Pointing a tag is safer when updating the master of `io-functions-commons`
---
> [#IOCOM-696] Replace master ref with the latest tag

- src/core/app_backend.tf
* [[#IOPID-1158] disabled clock skew events logging](https://github.com/pagopa/io-infra/commit/364ebeb0cf734da63f6ef8cc238accb95372f897)
disable the logging
---
> [#IOPID-1158] disable clock skew events logging

- src/core/README.md
- src/core/app_backend.tf
Upgrade Terraform modules for app backend L1
Upgrading Terraform modules in repos
---
> [EC-3] Upgrade appbackend L1 terraform modules

- src/core/README.md
- src/core/assets_cdn.tf
Upgrade CDN Terraform module
---
> [EC-5] Upgrade CDN module

- .identity/.terraform.lock.hcl
- .identity/03_github_environment_cd.tf
- .identity/03_github_environment_ci.tf
- .identity/04_github_identity.tf
- .identity/99_main.tf
- .identity/99_variables.tf
- .identity/env/prod/terraform.tfvars
Add managed identities federated with GitHub to use a passwordless approach in pipeline definitions
Simplicity
---
> feat: Introduce GitHub federated managed identities

- src/core/README.md
- src/core/continua_dynamiclink.tf
Upgrade Continua resource modules
---
> [EC-11] Upgrade Continua resource modules

- src/core/README.md
- src/core/nat_gateway.tf
Upgrade Nat Gateway Terarform module
---
> [EC-16] Upgrade nat gateway module

- src/core/README.md
- src/core/appgateway.tf
Upgrade application gateway module
---
> [EC-10] Upgrade core app gateway module

- src/core/README.md
- src/core/redis.tf
Upgrade Redis Cache module
---
> [EC-18] Upgrade Redis Terraform module

- src/.template-app/env/weu-beta/terraform.tfvars
- src/.template-app/env/weu-prod01/terraform.tfvars
- src/aks-platform/env/weu-beta/terraform.tfvars
- src/domains/citizen-auth-app/env/weu-beta/terraform.tfvars
- src/domains/citizen-auth-app/env/weu-prod01/terraform.tfvars
- src/domains/ioweb-app/env/weu-prod01/terraform.tfvars
- src/domains/messages-app/02_namespace.tf
- src/domains/messages-app/README.md
- src/domains/messages-app/env/weu-beta/terraform.tfvars
- src/domains/messages-app/env/weu-prod01/terraform.tfvars
- src/domains/payments-app/02_namespace.tf
- src/domains/payments-app/README.md
- src/domains/payments-app/env/weu-beta/terraform.tfvars
- src/domains/payments-app/env/weu-prod01/terraform.tfvars
- src/domains/profile-app/env/weu-beta/terraform.tfvars
- src/domains/profile-app/env/weu-prod01/terraform.tfvars
> Recreate AKS cluster with overlay mode

- src/core/README.md
- src/core/app_backend.tf
Upgrade modules for app backend l2 and li (app service + plan + staging slot)
Before merging, the state file shall be migrated to the new resources
---
> [EC3] Upgrade app backend app services to new Terraform modules

- src/core/README.md
- src/core/function_admin.tf
Upgrade function TF modules
---
> [EC-20] Upgrade function admin TF modules

- src/core/README.md
- src/core/app_messages.tf
- src/core/env/prod/backend.tfvars
Upgrade modules used by app messages domain
---
> [EC-9] Upgrade app messages TF modules

- src/domains/elk/.terraform.lock.hcl
- src/domains/elk/02_namespace.tf
> Fix validate

- src/core/README.md
- src/core/function_app.tf
> [EC-23] Upgrade TF modules for "app" function app

- src/core/README.md
- src/core/function_cgn.tf
- src/core/function_cgn_merchant.tf
> [EC-25] Upgrade TF modules of cgn functions

- src/core/README.md
- src/core/function_devportal_service_data.tf
> [EC-26] Upgrade dev portal function TF modules

- src/core/README.md
- src/core/function_eucovidcert.tf
> [EC-28] Upgrade eucovid cert function app TF modules

- src/core/README.md
- src/core/function_messages_cqrs.tf
> [EC-29] Upgrade messages cqrs function TF modules

- src/core/README.md
- src/core/function_services.tf
Upgrade function TF modules
---
> [EC-31] Upgrade function services TF modules

- src/core/README.md
- src/core/function_shared.tf
Upgrade function shared modules
---
> [EC-32] Upgrade function shared TF modules

- src/core/README.md
- src/core/function_elt.tf
Upgrade ELT function modules
---
> [EC-27] Upgrade ELT function modules

- src/core/README.md
- src/core/function_public.tf
- src/core/function_publiceventdispatcher.tf
> [EC-30] Upgrade function public TF modules (PT1)

- src/core/README.md
- src/core/selfcare.tf
> [EC-35] Upgrade "selfcare" resources TF modules

- src/core/app_messages.tf
- src/core/function_admin.tf
- src/core/function_app.tf
- src/core/function_app_async.tf
- src/core/function_assets_cdn.tf
- src/core/function_elt.tf
- src/core/function_eucovidcert.tf
- src/core/function_messages_cqrs.tf
- src/core/function_publiceventdispatcher.tf
- src/core/function_services.tf
- src/core/selfcare.tf
Set app service plan worker count property to null
Indicating a digit, forces the plan to scale up or down at the apply phase
---
> [EC-36] Set app service plan worker count value to null

- src/core/README.md
- src/core/function_publiceventdispatcher.tf
Migrate TF modules switching to linux app service plan
Upgrading all core modules and there is no windows module
---
> [EC-30] Migrate plan-fnpblevtdispatcher service plan to linux

- src/core/00_github_runner.tf
- src/core/README.md
> [EC-37] Upgrade GitHub runner TF module

- src/core/README.md
- src/core/app_messages.tf
- src/core/function_devportal_service_data.tf
- src/core/function_elt.tf
- src/core/function_messages_cqrs.tf
- src/core/function_publiceventdispatcher.tf
- src/core/function_subscription_migrations.tf
- src/core/redis.tf
- src/core/storage_api.tf
> [#IOPLT-205] Align Storage accounts to GRS

- src/domains/citizen-auth-common/03_storage.tf
- src/domains/ioweb-common/03_storage.tf
> [#IOPID-1221]  Fix immutable storages

- src/core/env/prod/terraform.tfvars
- src/core/redis.tf
Deletes unused variable
Terraform shows a warning with the deleted variables as unused
---
> [EC-34] Remove unused variables from core

- .identity/04_github_identity.tf
`github_federated_identity` module came with a bugfix
---
> [EC-53] Upgrade .identity modules

- src/core/README.md
- src/core/data.tf
- src/core/function_app.tf
- src/core/function_public.tf
add environment variables required by unique email enforcement to `functions-app` and `functions-public`
---
> build(uee): [IOPID-1259] add environment variables for fn-app and fn-public

- src/domains/messages-common/01_network.tf
- src/domains/messages-common/03_database.tf
- src/domains/messages-common/README.md
> Added dns zone to cosmos remote content

- src/domains/citizen-auth-app/06_storage.tf
- src/domains/citizen-auth-app/07_function_fast_login.tf
- src/domains/citizen-auth-app/README.md
This PR depends on https://github.com/pagopa/io-infra/pull/778
Switch to newly created immutable audit log storage
---
> [#IOPID-1221]  Switch audit log storage

- src/domains/ioweb-common/10_spid_login.tf
* [[#IOPID-1237] removed SPID_VALIDATOR_URL variable](https://github.com/pagopa/io-infra/commit/477d4f76dc28a5ca51dc6d1973c71c45a7d5fa7b)
disable SPID validator
---
> [#IOPID-1237] remove SPID_VALIDATOR_URL variable

- src/github-runner/README.md
- src/github-runner/container_app_jobs.tf
Add io-services-cms to supported repos
`io-services-cms` needs to run GitHub Actions on private runners. This PR adds the watcher on that repo
---
> [EC-61] Add io-services-cms repository to GitHub private runner

- src/domains/ioweb-common/03_storage.tf
- src/domains/ioweb-common/README.md
* [[#IOPID-1253] created new blob container with custom policy](https://github.com/pagopa/io-infra/commit/f3e139ff7078700ce1046db7575d17b5ed69a9ff)
creating new blob container dedicated to audit logs
---
> [#IOPID-1253] audit log container with custom policy

- .github/workflows/ioweb_prod_cd.yml
- .github/workflows/prod_cd_citizen-auth.yml
Add setup pipeline
Add setup step
New runners are randomly created so Terraform must be installed every time
---
> [EC-68] Add missing Terraform setup in CD pipelines

- .github/workflows/ioweb_prod_cd.yml
- .github/workflows/prod_cd_citizen-auth.yml
Refactor pipeline to make them work
Runners are now ephemeral and several changes were required to make them work correctly
---
> [EC-68] Resolve issues with CD pipelines

- src/core/README.md
- src/core/devportal.tf
- src/core/selfcare.tf
Add API_SERVICES_CMS_* env vars to devportal
- [add API_SERVICES_CMS_* env vars to devportal](https://github.com/pagopa/io-infra/commit/b48e6354f3294100dae916f30ab90f5a0b2b10fb)
See [RFC](https://pagopa.atlassian.net/wiki/spaces/IOPAE/pages/862126207/RFC+0016+-+Parallel+running+tra+CMS+Servizi+e+Dev+Portal)
---
> [IOPAE-907] add env vars to devportal

- src/domains/sign/landing.tf
> [#IOPLT-319] Align IO-Sign Domain Storage accounts SKU

- src/core/function_app.tf
- src/core/function_app_async.tf
> [#IOPID-1197] Added env variables to fn-app

- src/core/README.md
- src/core/function_app_async.tf
> [#IOPID-1197] Add new lease collection

- src/core/function_app.tf
- src/core/function_app_async.tf
> enabled OnProfileUpdate trigger

- src/core/env/prod/terraform.tfvars
Change the minimum autoscale instances for `fn-app-async`
The fisical partition for Profile collection is `8`, we will use the same number of minimum instances for `io-fn-app-async` during unique email table seeding.
---
> Align seeding min instance App Async

- src/domains/citizen-auth-common/04_redis_common.tf
Increase capacity from 0 to 1
Increment the maximum number of connection to 1000
---
> [#IOPID-1134] Scale citizen-auth redis to C1

- src/github-runner/README.md
- src/github-runner/container_app_environment.tf
- src/github-runner/container_app_jobs.tf
- src/github-runner/data.tf
- src/github-runner/env/prod/terraform.tfvars
- src/github-runner/outputs.tf
- src/github-runner/resource_groups.tf
- src/github-runner/subnet.tf
- src/github-runner/variables.tf
Use the new versions of the modules
Following the long discussion with the Azure Container App product team, we need to create a container app job for each repository instead of a single one with multiple containers in it.
In fact, the approach we've been using prevents the correct shut down of the container, resulting in a deadlock.
---
> [EC-80] Refactoring github runner module

- src/domains/sign/99_variables.tf
- src/domains/sign/env/prod/terraform.tfvars
- src/domains/sign/github_runner.tf
Add container app job definition to terraform
Each repo has its own container app job
---
> [EC-85] Add GitHub private runner on Container App job

- src/domains/ioweb-app/03_storage.tf
- src/domains/ioweb-app/05_resource_group.tf
- src/domains/ioweb-app/06_function_ioweb_profile.tf
- src/domains/ioweb-app/README.md
Add new `AUDIT_LOG_CONNECTION_STRING` and `AUDIT_LOG_CONTAINER` variables
Allow the BFF to store Audit Logs
---
> [#IOPID-1342] Add Audit Log env vars to io-web function

- .github/workflows/ioweb_prod_cd.yml
Add az login action
Pipeline is broken
---
> [EC-92] Fix ioweb CD pipeline

- src/core/README.md
- src/core/dns_io_pagopa_it.tf
Add DNS A record
DNS record to be used for FIMS apis
---
> [IOCOM-469] Add DNS A record for openid-provider

- src/core/function_admin.tf
> [#IOPID-1030] Added profileEmails-variables to fn-admin

- src/domains/citizen-auth-app/07_function_fast_login.tf
- src/domains/citizen-auth-common/03_apim_v2.tf
- src/domains/citizen-auth-common/99_locals.tf
- src/domains/citizen-auth-common/README.md
- src/domains/citizen-auth-common/api/fast_login/v1/_openapi.yaml
- src/domains/citizen-auth-common/api/fast_login/v1/policy.xml
- src/domains/citizen-auth-common/api/io_lollipop/v1/_openapi.yaml
- src/domains/citizen-auth-common/api_product/fast_login_operation/_base_policy.xml
Enable APIM subnet for `fn-fast-login`
Create Group, User, Subscription and Operation for APIM api (lock/unlock for Operation)
Policy to generate `unlock_code` automatically.
PagoPa Operation needs API to manage unlock and lock operation for the user that cannot execute them from IO Web.
---
> [#IOPID-1309] Operation Subscription and Group for FastLogin lock/unlock functions

- src/domains/citizen-auth-common/api/fast_login/v1/_openapi.yaml
Add `/` in fast login openapi paths
---
> [#IOPID-1309] Fix fast login openapi paths

- src/domains/citizen-auth-common/api/fast_login/v1/policy.xml
> [#IOPID-1309] Fix missing chose on APIM policy

- src/github-runner/README.md
- src/github-runner/container_app_environment.tf
- src/github-runner/container_app_jobs.tf
Upgrade container app job modules
New modules contains new github runner base image
---
> [EC-104] Upgrade container app job modules

- src/core/app_backend.tf
- src/core/function_app.tf
- src/core/function_public.tf
- Set `FF_UNIQUE_EMAIL_ENFORCEMENT` to `ALL` on appbackend, fn_app, fn_public
- Set `IS_SPID_EMAIL_PERSISTENCE_ENABLED` to `false`
Enable UIM for all users
---
> [#IOPID-1179] enable UIM for all users

- src/core/app_backend.tf
Set `FF_FAST_LOGIN` to `ALL`
Enable Fast Login for all user
---
> [#IOPID-1338] Set `FF_FAST_LOGIN` to `ALL`

- src/domains/ioweb-app/06_function_ioweb_profile.tf
Set `FF_API_ENABLED` to `ALL`
Open ioweb to all users
---
> [#IOPID-1340] Open ioweb to all users

- src/domains/sign/io_sign_issuer_func.tf
- src/domains/sign/key_vault.tf
Add `IoServicesSubscriptionKey` to `io-p-sign-issuer-func`
---
> feat(io-sign): [SFEQS-2097] Add environment variable

- src/domains/citizen-auth-common/api/fims/admin/_swagger.json.tpl
- src/domains/citizen-auth-common/api/fims/public/_swagger.json.tpl
Added some endpoints, and moved others.
Some endpoints were not exposed and apim was returning a 404.
Other endpoint were splitted in the wrong openapi.
> Updated FIMS specs

- src/domains/citizen-auth-common/api/fims/public/_swagger.json.tpl
> Added FIMS endpoint

- src/domains/sign/env/prod/terraform.tfvars
- src/domains/sign/io_sign_issuer_func.tf
1. Updated env variables for `io-p-sign-backoffice-func`
2. Disabled function `CreateIssuer` in `io-p-sign-issuer-func`
The function `CreateIssuer` in `io-p-sign-issuer-func` is temporarily replaced with `OnSelfcareContractsMessage` in `io-p-sign-backoffice-func`
---
3. select PR branch
4. wait for approval
> [SFEQS-2025] Updated env variables for back office function app and disabled CreateIssuer function

- src/domains/sign/io_sign_backoffice_func.tf
Add value to `sticky_app_setting_names` variable for not swapping disabled property for `onSelfcareContractsMessage` function
---
> Update `io_sign_backoffice_func` module

- src/domains/citizen-auth-common/api/fims/public/_swagger.json.tpl
> added jwks endpoint

- src/core/99_variables.tf
- src/core/README.md
- src/core/dns_io_italia_it.tf
- src/core/private_dns_zones.tf
Default value goes from 3600 seconds to 60
We are migrating the Application Gateway, so TTL must be reduced to swap IPs
---
> [EC-163] Reduce Application Gateway's DNS TTL 

- src/core/appgateway_temp.tf
- src/core/dns_firmaconio_selfcare_pagopa_it.tf
- src/core/dns_io_italia_it.tf
- src/core/dns_io_pagopa_it.tf
- src/core/dns_io_selfcare_pagopa_it.tf
> [#IOPLT-208] Add Temp App GW Public IP to DNS Record

- src/domains/ioweb-common/06_cdn.tf
- src/domains/ioweb-common/README.md
Enable CDN
We need diagnostic tools
---
> [EC-172] Enable logs on ioweb CDN endpoint

- src/domains/sign/monitoring.tf
1. Add alert on `REJECTED` requests
This alarm allows us to monitor for `REJECTED` signature requests, so we can proactively resolve the issue.
---
> [SFEQS-2029] Add REJECTED requests alert

- src/core/README.md
- src/core/redis.tf
Delete `iopstredis` resource
Not used anymore
---
> [EC-177] Delete old Redis storage account

- src/core/app_backend.tf
Restore variables `BONUS_API_URL` and `BONUS_API_KEY`
The restored variables are required to `io-backend` startup. They must be removed after the upgrade of `io-backend` on both prod and stage slots.
---
There is a drift in configuration about:
-  `Advanced Threat protection` for storage_api_replica, storage_api and redis_common_backup_zrs
- `Linux Virtual Machine Scale Set` for io-p-azdoa-vmss-loadtest-li
See the apply report for more detail [here](https://dev.azure.com/pagopaspa/io-platform-iac-projects/_build/results?buildId=143983&view=logs&j=a64d7b47-1ed8-5b6a-1a91-9630d50f8660&t=6845a996-e370-5987-b9c0-28d90f08d8d0 ) …
> Restore dummy values for required io-backend configuration variables

- src/domains/citizen-auth-app/04_fims.tf
- src/domains/citizen-auth-app/05_database.tf
- src/domains/citizen-auth-app/README.md
- src/domains/citizen-auth-common/.terraform.lock.hcl
- src/domains/citizen-auth-common/01_network.tf
- src/domains/citizen-auth-common/02_key_vault.tf
- src/domains/citizen-auth-common/03_apim_v2.tf
- src/domains/citizen-auth-common/03_storage.tf
- src/domains/citizen-auth-common/04_redis_common.tf
- src/domains/citizen-auth-common/05_database.tf
- src/domains/citizen-auth-common/99_main.tf
- src/domains/citizen-auth-common/README.md
Storage Account migration
TF modules migration
Saving costs with the new pricing model
New modules version constraints
---
> [EC-196] Module migration and ioplollipopassertionsst migration to new Defender

- src/domains/citizen-auth-common/05_database.tf
- src/domains/citizen-auth-common/env/prod/terraform.tfvars
- [increase lollipop-pubkeys throughput, move alerts to prod channel](https://github.com/pagopa/io-infra/commit/d0d6d86f9d70889b39fc0e7c86e4e3786ab03588)
The maximum number of RU has been reached. 
---
> [#IOPID-1597] Increase `lollipop-pubkeys`max throughput

- src/core/app_backend.tf
- src/core/env/prod/terraform.tfvars
- [added new env var PN_CONFIGURATION_ID](https://github.com/pagopa/io-infra/commit/713fc04df6d737581bbf6a89cd8a6b89cbd07a30)
Created a new env var to manage the remote content configuration ID of PN
---
> [#IOCOM-1031] added new env var PN_CONFIGURATION_ID

- src/domains/citizen-auth-app/04_function_lollipop.tf
- src/domains/citizen-auth-app/07_function_fast_login.tf
- src/domains/citizen-auth-common/env/prod/terraform.tfvars
- [increase lollipop-pubkeys RU](https://github.com/pagopa/io-infra/pull/890/commits/a424534009085b2ac7c5ba333ea04562daa7e6f5)
- [update scaling for fn-lollipop and fn-fast-login](https://github.com/pagopa/io-infra/pull/890/commits/c1af7bb7b24c326da1f4d3bac48b931afa37d62f)
Improving the scalability responsiveness of the function
---
> [#IOPID-1607/1] Update scaling rules of `citizen-auth` domain functions

- .github/workflows/gh_runner-scheduler.yml
- .github/workflows/ioweb_prod_cd.yml
- .github/workflows/ioweb_prod_ci.yml
- .github/workflows/ioweb_prod_drift.yml
- .github/workflows/prod_cd_citizen-auth.yml
- .github/workflows/prod_ci_citizen-auth.yml
- .github/workflows/prod_drift_citizen-auth.yml
- .github/workflows/static_analysis.yml
Upgrade `checkout` action version
Upgrade `azure login` action version
Older versions use node16 which is deprecated. A warning appeared in GitHub
---
> Upgrade pipelines action versions 

- src/core/appgateway.tf
Explicit query string forwarding
Query strings not reaching apis
---
> [EC-214] Add query string forwarding to openid-provider rewrite rules

- src/domains/messages-common/03_database.tf
- src/domains/messages-common/README.md
This collection is no longer needed
---
> [#IOCOM-1138] Remove old and unused collection for RC

- src/core/99_variables.tf
- src/core/README.md
- src/core/env/prod/terraform.tfvars
- src/core/network.tf
- src/core/private_dns_zones.tf
> [#IOPLT-328] Add Italy North VNET + peering

- src/core/99_variables.tf
- src/core/README.md
- src/core/cgn.tf
- src/core/env/prod/terraform.tfvars
- src/core/function_cgn.tf
- src/core/function_cgn_merchant.tf
- src/domains/cgn/_modules/networking/data.tf
- src/domains/cgn/_modules/networking/locals.tf
- src/domains/cgn/_modules/networking/main.tf
- src/domains/cgn/_modules/networking/subnet_cgn.tf
- src/domains/cgn/_modules/networking/subnet_cgn_redis.tf
- src/domains/cgn/_modules/networking/variables.tf
- src/domains/cgn/prod/westeurope/.terraform.lock.hcl
- src/domains/cgn/prod/westeurope/README.md
- src/domains/cgn/prod/westeurope/networking.tf
Move subnet definitions in their own configuration
CGN refactoring
---
> [EC-207] Move CGN networking-resources in their own configuration 

- src/core/README.md
- src/core/cgn.tf
- src/domains/cgn/_modules/networking/outputs.tf
- src/domains/cgn/_modules/redis/data.tf
- src/domains/cgn/_modules/redis/main.tf
- src/domains/cgn/_modules/redis/outputs.tf
- src/domains/cgn/_modules/redis/redis_cgn.tf
- src/domains/cgn/_modules/redis/variables.tf
- src/domains/cgn/prod/westeurope/.terraform.lock.hcl
- src/domains/cgn/prod/westeurope/README.md
- src/domains/cgn/prod/westeurope/main.tf
- src/domains/cgn/prod/westeurope/redis.tf
Move Redis resources in their own configuration
CGN refactoring
---
> [EC-207] Move CGN redis-resources in their own configuration

- .github/labeler.yml
- .github/workflows/call_code_review.yaml
- .github/workflows/call_release.yaml
- .github/workflows/cgn_cd.yaml
- .github/workflows/cgn_ci.yaml
- .github/workflows/pr_labeler.yaml
Add labeler
Add CI/CD workflows
Automation
---
> [EC-207] Add workflows for CGN workspace

- src/core/README.md
- src/core/devportal.tf
- src/core/function_devportal_service_data.tf
- src/core/function_subscription_migrations.tf
- src/core/selfcare.tf
- src/domains/selfcare/_modules/networking/data.tf
- src/domains/selfcare/_modules/networking/main.tf
- src/domains/selfcare/_modules/networking/outputs.tf
- src/domains/selfcare/_modules/networking/subnet_selfcare_be_common.tf
- src/domains/selfcare/_modules/networking/variables.tf
- src/domains/selfcare/prod/westeurope/.terraform.lock.hcl
- src/domains/selfcare/prod/westeurope/README.md
- src/domains/selfcare/prod/westeurope/networking.tf
Move io selfcare network-related resources to their own configuration
---
> [EC-216] Move io selfcare network-related resources to their own configuration

- src/core/README.md
- src/core/monitor.tf
- src/core/selfcare.tf
- src/domains/selfcare/_modules/cdn/cdn_selfcare.tf
- src/domains/selfcare/_modules/cdn/data.tf
- src/domains/selfcare/_modules/cdn/main.tf
- src/domains/selfcare/_modules/cdn/outputs.tf
- src/domains/selfcare/_modules/cdn/variables.tf
- src/domains/selfcare/prod/westeurope/.terraform.lock.hcl
- src/domains/selfcare/prod/westeurope/README.md
- src/domains/selfcare/prod/westeurope/cdn.tf
Move io selfcare CDN resources to their own configuration
---
> [EC-216] Move io selfcare CDN resources to their own configuration

- .github/workflows/ioselfcare_cd.yaml
- .github/workflows/ioselfcare_ci.yaml
- .github/workflows/static_analysis.yml
> [EC-216] Add CI/CD workflows for selfcare domain

- src/domains/eucovidcert/prod/westeurope/locals.tf
> [EC-217] Update tags and use a single file

- src/core/README.md
- src/core/app_messages.tf
- src/domains/messages-common/.terraform.lock.hcl
- src/domains/messages-common/01_network.tf
- src/domains/messages-common/02_key_vault.tf
- src/domains/messages-common/03_database.tf
- src/domains/messages-common/04_storage.tf
- src/domains/messages-common/05_apim_v2.tf
- src/domains/messages-common/07_redis.tf
- src/domains/messages-common/99_main.tf
- src/domains/messages-common/README.md
- src/domains/messages-common/env/prod/terraform.tfvars
Move messages common resources in their own configuration
---
> [EC-239] Move messages common resources in their own configuration

- src/domains/messages-common/05_apim_v2.tf
- src/domains/messages-common/README.md
> Revert "[#IOCOM-1202] Added new manage API to IO SERVICES API"

- src/domains/messages-common/05_apim_v2.tf
- src/domains/messages-common/README.md
> Revert "Revert "[#IOCOM-1202] Added new manage API to IO SERVICES API""

- src/core/99_variables.tf
- src/core/README.md
- src/core/backend_messages.tf
- src/core/env/prod/terraform.tfvars
- src/core/function_assets_cdn.tf
- src/domains/messages-app/11_function_cqrs.tf
- src/domains/messages-app/99_variables.tf
- src/domains/messages-app/README.md
- src/domains/messages-app/env/weu-beta/terraform.tfvars
- src/domains/messages-app/env/weu-prod01/terraform.tfvars
Move Function messages cqrs resources to their own configuration
---
> [EC-240] Move Function messages cqrs resources to their own configuration

- src/domains/messages-app/12_function_service_messages.tf
- src/domains/messages-app/99_variables.tf
- src/domains/messages-app/README.md
- src/domains/messages-app/env/weu-beta/terraform.tfvars
- src/domains/messages-app/env/weu-prod01/terraform.tfvars
Added new azure functions and their dependencies to deploy the `io-functions-service-messages`.
We need to migrate `io-functions-service-messages` outside AKS.
> [#IOCOM-1220] Created new functions for Service Messages

- .github/workflows/continua_cd.yaml
- .github/workflows/continua_ci.yaml
> [EC-243] Add workflows for Continua infrastructure

- src/domains/messages-common/03_database.tf
- src/domains/messages-common/README.md
Added new sharded collection for reminder.
We need to migrate to a partitioned collection.
---
> added new sharded collection for reminder

- .github/workflows/ioweb_prod_cd.yml
- .github/workflows/ioweb_prod_ci.yml
- .github/workflows/ioweb_prod_drift.yml
- .github/workflows/prod_cd_citizen-auth.yml
- .github/workflows/prod_ci_citizen-auth.yml
- .github/workflows/prod_drift_citizen-auth.yml
Updates variable names to perform Azure login
Previous variables have been deleted
---
> [EC-259] Fix Azure authentication in workflows

- src/core/app_backend.tf
- src/core/env/prod/terraform.tfvars
- src/core/function_app.tf
- src/core/function_app_async.tf
- src/domains/citizen-auth-app/04_function_lollipop.tf
- src/domains/citizen-auth-app/07_function_fast_login.tf
- src/domains/citizen-auth-app/env/weu-prod01/terraform.tfvars
- src/domains/ioweb-app/06_function_ioweb_profile.tf
- src/domains/ioweb-app/env/weu-prod01/terraform.tfvars
- src/domains/messages-app/10_function_messages.tf
> Increase io-be instances

- .github/workflows/core_code_review.yaml
Add CI workflow
Validate code when opening a PR
---
> [EC-260] Add CI workflow for ItalyNorth core infra

- src/domains/ioweb-common/06_cdn.tf
- Add bypass rule strategy for html files
Random errors while deploying new site version to CDN, due to caching strategies and cleanup delays.
ℹ️  This PR aligns the code with what's already implemented by @arcogabbo in the infrastructure. Apply is not necessary.
---
> [#IOPID-1703] Add `TakeRootFilesFromStorage` rule to ioweb CDN

- src/core/README.md
- src/core/private_dns_zones.tf
Added ai search private dns zone
AI Search is being implemented in the io-services-cms domain
- [ X ] Add new resources
- [ X ] PROD
- [ X ] No
---
> EC-234 - Added ai search private dns zone

- src/core/_modules/networking/data.tf
- src/core/_modules/networking/private_dns_zone_itn_common.tf
Added ai search private dns zone network link
AI Search is being implemented in io-services-cms domain
- [ X ] Add new resources
- [ X ] PROD
- [ X ] No
- [ X ] No
---
> EC-234 - Added ai search private dns zone network link

- src/domains/messages-common/api/service-messages/v1/_base_policy.xml
Changed backend base url to point io-p-messages-sending-func
We moved the services-messages functions from AKS to Azure Functions.
> [IOCOM-1233] Changed backend base url

- src/domains/messages-common/05_apim_v2.tf
- src/domains/messages-common/api/service-messages/v1/_base_policy.xml
Added name value to apim for sending fn key.
Added fnkey to apim headers to reach sending-func.
We need to close these funcs to apim only.
> [IOCOM-1291] Added fn key to apim

- src/domains/citizen-auth-app/04_function_lollipop.tf
- src/domains/citizen-auth-app/07_function_fast_login.tf
- src/domains/citizen-auth-app/env/weu-prod01/terraform.tfvars
> [#IOPID-1780] Set basic, morning and evening profiles for `fn-lollipop` and `fn-fast-login`

- src/domains/citizen-auth-app/01_network.tf
- src/domains/citizen-auth-app/08_session_manager.tf
* [[#IOPID-1765] aligned resources](https://github.com/pagopa/io-infra/commit/a961ad657e12493869b6402a8314dbd62436960d)
align IAC to existing resources
---
> [#IOPID-1765] aligned resources

- src/domains/citizen-auth-app/08_session_manager.tf
- Set session-manager slot staging name to `staging`
⚠️  Manually applied.
---
> [#IOPID-1794] fix slot staging name

- src/core/README.md
- src/core/private_dns_zones.tf
Attach AI search private dns zone to the weu common VNet
- [ X ] Add new resources
- [ X ] PROD
- [ X ] No
- [ X ] Yes
---
> EC-234 - Attach AI search private dns zone to the weu common VNet

- src/domains/citizen-auth-app/01_network.tf
- src/domains/citizen-auth-app/08_session_manager.tf
- src/domains/citizen-auth-app/README.md
⚠️ manually applied
* [[#IOPID-1764] add runner vnet to staging slot](https://github.com/pagopa/io-infra/commit/e3a012b351ecdfc9ecd67f8fc5e7b1e7141a7ed5)
---
> [#IOPID-1764] add runner vnet to staging slot

- src/core/_modules/networking/snet_private_endpoints.tf
- src/core/_modules/networking/vnet_common.tf
- src/core/_modules/networking/vnet_peering_itn_common_to_weu_beta.tf
- src/core/_modules/networking/vnet_peering_itn_common_to_weu_prod.tf
- src/core/_modules/networking/vnet_peering_weu_to_itn_common.tf
- src/core/prod/italynorth/.terraform.lock.hcl
- src/core/prod/italynorth/README.md
- src/core/prod/italynorth/main.tf
- src/domains/citizen-auth-app/.terraform.lock.hcl
- src/domains/citizen-auth-app/01_network.tf
- src/domains/citizen-auth-app/08_session_manager.tf
- src/domains/citizen-auth-app/README.md
Rename ItalyNorth resources with [new naming convention](https://pagopa.atlassian.net/wiki/spaces/DevEx/pages/1032880258/Azure+Naming+convention+risorse+Italy+North) 
A new naming convention is agreed
---
> [EC-274] Rename ItalyNorth resources

- .github/workflows/call_code_review.yaml
- .github/workflows/call_release.yaml
- .github/workflows/gh_runner-scheduler.yml
- .github/workflows/ioweb_prod_cd.yml
- .github/workflows/prod_cd_citizen-auth.yml
Upgrade Az Login GitHub Action to 2.1.0
Old one is broken
---
> Upgrade az login GitHub Action

- src/core/README.md
- src/core/function_app.tf
- src/core/storage_api.tf
- src/domains/citizen-auth-app/08_session_manager.tf
- src/domains/citizen-auth-app/README.md
* [[#IOPID-1800] added session-manager subnet to fn-app](https://github.com/pagopa/io-infra/commit/0b17264cec8ed3d4bf3a4dd5b7b3a885670d44e4)
* [[#IOPID-1800] added fn-app required env vars for session-manager](https://github.com/pagopa/io-infra/commit/4692f24b03bdec589dc407907af9210ae387cd57)
add required subnet and env vars for session-manager
---
> [#IOPID-1800] session-manager updates

- src/domains/citizen-auth-app/01_network.tf
- src/domains/citizen-auth-app/08_session_manager.tf
- src/domains/citizen-auth-app/README.md
- src/domains/citizen-auth-app/env/weu-prod01/terraform.tfvars
> [EC-276] Move session manager in WEU (temporarely)

- CODEOWNERS
Add engineering-team-cloud-eng as CODEOWNERS of infra and github paths
---
> Add engineering-team-cloud-eng as CODEOWNERS

- src/notification-hubs/prod/notification_hub_ntfns_common_partition_1.tf
- src/notification-hubs/prod/notification_hub_ntfns_common_partition_2.tf
- src/notification-hubs/prod/notification_hub_ntfns_common_partition_3.tf
- src/notification-hubs/prod/notification_hub_ntfns_common_partition_4.tf
* Increase the treshold of the alert
We do not want the alert to fire at the actual rate
---
> Increase NH Push notification Service error alert treshold

- src/domains/functions/function_services.tf
> Revert "Disable messages functions"

- src/domains/citizen-auth-common/env/prod/terraform.tfvars
increase `session-notifications` provisioned RU avoiding 429s cosmos errors and speedup ExpiredSessionDiscoverer timerTrigger
> increase session-notifications RU

- src/domains/citizen-auth-common/03_storage.tf
- src/domains/citizen-auth-common/README.md
Remove queues:
- `pubkeys-revoke`
- `pubkeys-revoke-v2`
> [#IOPID-3151] Remove old queue

- src/legacy-apim/prod/api/io_services/v1/policy.xml
open 5% traffic to new service-itn function using apim policy
> [#IOPLT-1282]open traffic to new service-itn function using apim policy
