pagopa/io-infra

- src/core/README.md
- src/core/dns_io_italia_it.tf
migrate api.io.italia.it on new app gateway
- cost savings
- listener issue on old app gateway
How to apply
```
bash terraform.sh import prod azurerm_dns_a_record.api_io_italia_it "/subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-rg-external/providers/Microsoft.Network/dnszones/io.italia.it/A/api"
bash terraform.sh apply prod
bash terraform.sh apply prod
```
---
> [INFRA-290] Migrate api.io.italia.it on new app gateway

- .devops/code-review-pipelines.yml
- src/core/README.md
- src/core/appgateway.tf
- src/core/dns_io_italia_it.tf
- src/core/env/prod/terraform.tfvars
- src/core/monitor.tf
- change dns record `app-backend.io.italia.it` to use new app gateway
- scale up new app gateway to min 3 instances
- send logs to internal log_analytics_workspace
reduce over provisioned resources
before apply run
```
bash terraform.sh import prod azurerm_dns_a_record.app_backend_io_italia_it "/subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-rg-external/providers/Microsoft.Network/dnszones/io.italia.it/A/app-backend"
```
---
> [INFRA-291] Migrate to new app backend for io app

- src/core/dns_io_italia_it.tf
- src/core/env/prod/terraform.tfvars
- increase min app gateway instances to 3 (rule is compute units peak/10 -> so 30/10=3)
- increase dns ttl to default value for app-backend.io.italia.it
---
> Increase app gateway min instances

- src/core/function_elt.tf
- add connection strings to `io-p-cosmos-api-northeurope`
- add connection string to `iopstapireplica`
- add connection string to `iopstcdnassets` for reading `visible-services-extended.json`
- add new blob containers `messages-report-step1` and `messages-report-step-final`
- add new variable for new handlers, used for tuning cosmos and blob storage queries
In order to retrieve aggregated data for messages, ad new handler triggered by a command from EH topic that will scan messages and write a csv with required aggregated data.
NOTE: this is just a workaroud to get data quickly.
---
> [IC-134] New env variable for messages report

- src/core/function_elt.tf
- Setup cosmos variables after tuning
- Add `COSMOSDB_REPLICA_LOCATION` new variable
- Add new `fneltexports` table
---
> [IC-134] Setup cosmos variables after tuning

- src/core/selfcare.tf
Cleanup unused `SELFCARE_IDP_ISSUER_JWT_SIGNATURE_KEY` env var.
To be applied and merged after https://github.com/pagopa/io-developer-portal-backend/pull/152 and https://github.com/pagopa/io-infra/pull/67 are deployed
> [#IC-160] Implement jwk signature verification on `SelfCare IO` (cleanup)

- src/core/function_subscription_migrations.tf
* disable `OnServiceChange` function on both prod and staging slot
* configure connection to `IO`'s main cosmosdb
* configure connection to APIM
* configure connection to local PostgreSQL db (to be completed)
As we are implementing this https://github.com/pagopa/io-subscription-migration/pull/10
---
> [#IC-185] Add environment configs for `subscription-migrations`

- src/core/function_subscription_migrations.tf
* declare `QUEUE_SUBSCRIPTION_TO_MIGRATE` queue
* disable `ChangeOneSubscriptionOwnership` in staging slot to prevent it to consume production messages
Configuration to support https://github.com/pagopa/io-subscription-migration/pull/31
---
> [#IC-281] Configure queue handler `ChangeOneSubscriptionOwnership`

- src/core/function_subscription_migrations.tf
* disable `ChangeAllSubscriptionsOwnership` in staging slot to prevent it to consume production messages
* declare `QUEUE_ALL_SUBSCRIPTIONS_TO_MIGRATE` queue
Configuration to support https://github.com/pagopa/io-subscription-migration/pull/32
---
> [#IC-282] Disable stage slot for ChangeAllSubscriptionsOwnership and configure queue

- src/core/function_subscription_migrations.tf
- src/core/selfcare.tf
`io-p-app-selfcare-be` needs to reach `io-p-subsmigrations-fn`
---
> [#IC-256] Allow `io-p-app-selfcare-be` to reach `io-p-subsmigrations-fn` via VNET

- src/core/app_backend.tf
- src/core/env/prod/terraform.tfvars
We need to add a new hub in the IO EventHubs to implement a change data capture on the cosmos collection "message-status". This CDC will be used to materialize message data on a cosmos collection (now) and on an elastic index (later).
Add a new eventubs configuration on terreform prod env
This change will be a part of the solution for the message pagination and search feature
---
> [#IC-311] Add Event-hub for cosmos collection 'message-status'

- src/core/env/prod/terraform.tfvars
- src/core/function_elt.tf
- Added 3 new Event Hub topic: `pdnd-io-cosmosdb-messages`, `pdnd-io-cosmosdb-message-status`, `pdnd-io-cosmosdb-message-status`
- Added new tables for handling kafka failures: `fnelterrors_messages`, `fnelterrors_message_status`, `fnelterrors_notification_status`
- Set new env variables for enabling ChangeFeed leases over `messages`, `message-status` and `notification-status` collections
Enable sending message data to PDND
---
> [IC-364]  Add fn-elt variables

- src/core/app_backend.tf
- add new IS_APPBACKENDLI env variable in appbackend instances
- set it to true only or appbackend_li instance
Discriminate io-backend instance for enabling/disabling notify and session lock endpoints
---
> [ICC-113] [FIX] Add new IS_APPBACKENDLI env variable in appbackend instances

- src/core/README.md
- src/core/app_backend.tf
* set health check on `/ping` to enable automatic failover
* set 3 minutes as tolerance time span
Some instances of `appbackendl1`, `appbackendl2` and `appbackendli` start with bad operating system configuration and hence fail to serve requests. By enabling health checks, we can automatically remove such instances from load balancers and increase the overall system availability.
---
> [#IOPSC-24] Add healthcheck to appbackend instances

- src/core/README.md
- src/core/app_backend.tf
Add ENV variables to `io-backend` resources.
Two new key vault values are required (`appbackend-PN-API-KEY-ENV` e `appbackend-PN-API-KEY-UAT-ENV`).
To call the PN Activation service the backend requires some ENV variables that are added with this PR. The feature flags that enables the integration is temporarily disabled.
---
> [#IOCIT-74] Add PN Activation configuration

- src/core/app_backend.tf
Enable FF for PN Activation service
Change UAT service url for PN to DEV service url
UAT service url is temporarily unavailable, we update the configuration with DEV endpoint to complete an integration test with App and PN.
Enable the feature flag to activate the new endpoint in `io-backend`.  
---
> [#IOCIT-74] Change UAT PN endpoint to DEV, enable FF

- .devops/core-code-review-pipelines.yml
- .devops/messages-code-review-pipelines.yml
- .devops/payments-code-review-pipelines.yml
- .devops/profile-code-review-pipelines.yml
- .devops/sign-code-review-pipelines.yml
Added in all the code review pipelines the snippet:
```yaml
exclude:
- '**/*.lock.hcl'
```
Avoid code-review to run in case other commits, during pre-commit change the lock.hcl files in other folders
---
> fix: Avoid code review to run on lock.hcl files

- src/psql/selfcare/devportal-service-data/migrations/db/v3__schema_fixed.sql
Needs to alter column type for `RequireSecureChannels` in DeveloperPortalServiceData schema, cause we missed to specify the column type into boolean.
---
> Alter column type for DeveloperPortalServiceData schema

- src/core/function_elt.tf
Disable the legacy message-status change function for PDND to release the port&adapter one.
disable the CosmosApiMessageStatusChangeFeed function
Disable the current imeplementation to replace it with a refactored one that will manage errors using a storage queue. This will allow a better error manage.
---
> [#ICC-121] Disable message-status change feed function

- src/core/function_devportal_service_data.tf
This PR fix a Configuration Field name for Azure Function releated to devportalservicedata application
---
> Fix DB Schame Name to DeveloperPortalServiceData

- src/core/apim_io_admin_api.tf
- src/core/devportal.tf
- src/core/selfcare.tf
Due client configuration, we re-enable the http protocol on api management admin api
---
> fix: http fn-admin on apim

- src/domains/sign/api/issuer/v1/_base_policy.xml
- src/domains/sign/api_product/sign/_base_policy.xml
Remove references to user context in `api/issuer/v1/` base policy
The APIM subscriptions interacting with this API, are not binded to a user since user information are not required for the process to work. Therefore, referencing the user context raised an error in the policy evaluation, hence a 5xx HTTP response from the APIM.
---
> sign: remove user context

- src/core/app_backend.tf
- Add `LOLLIPOP_ALLOWED_USER_AGENTS` env variable
This is needed in order to restrict allowed user-agents that could initialize LolliPOP flow
---
> [#ICC-273] Configure LolliPOP allowed User-Agent

- src/core/terraform.sh
* Enable `force-unlock` in `./terraform.sh`
There are cases in which we may want to perform `force-unlock` to unlock the state. This may be in case of CI/CD pipeline failures or manual cancellation. 
The aim of the script is to provide the correct setup for the command to be executed.
**The script is meant to be executed by a human**, hence warnings are shown and manual input is required.
Should we want to have a dedicated pipeline? That would have the benefit of not having the command executed on a developer machine. However, this may _enforce focus_ on the operation being executed due to the script being interactive.
> Unlock script

- src/core/api/io_services/v1/post_submitmessageforuserwithfiscalcodeinbody_policy/policy.xml
#392 disable routing towards newly created `fn-eucovidcerts` as we were experiencing production issues. 
Once we apply #413 we can revert #392
Depends on #413
> Revert "fix: Enable routing to old fn-services"

- src/core/99_variables.tf
- src/core/README.md
- src/core/app_backend.tf
This PR adds the configuration needed to use third party messages with [io-sign](https://github.com/pagopa/io-sign).
- Added `io_sign_service_id` variable
- Added `io-sign` configuration to `THIRD_PARTY_CONFIG_LIST`
We have implemented the necessary endpoints on `io-sign` https://github.com/pagopa/io-sign/pull/78 to use third party messages for signed documents. Here the [openapi](https://raw.githubusercontent.com/pagopa/io-sign/8afb58882d179eacb955c48b55786ca469e3ab41/apps/io-func-sign-user/openapi.yaml)
---
> [#SFEQS-1401] Add io-sign third party configuration

- src/core/app_backend.tf
This PR fix a typo in `baseUrl` in `THIRD_PARTY_CONFIG_LIST`  [io-sign](https://github.com/pagopa/io-sign).
- Updated `io-sign` configuration to `THIRD_PARTY_CONFIG_LIST`
---
> [#SFEQS-1401]  Typo fix in io-sign baseUrl for third party messages

- src/core/99_variables.tf
- src/core/README.md
- src/core/app_backend.tf
- src/core/data.tf
- src/domains/citizen-auth-common/03_storage.tf
- src/domains/citizen-auth-common/99_locals.tf
See commit history
`io-backend` requires some ENVs variables to connect to the queue storage of `LolliPOP` domain to revoke older Pub Keys.
---
> [#IOCIT-363] Add required ENVs var for Lollipop Queue Storage in io-backend

- src/core/app_backend.tf
set FF_LOLLIPOP_ENABLED to 1 to enable LolliPoP flow
---
> enable Lollipop on `io-backend`

- .github/workflows/prod_cd_citizen-auth.yml
- .github/workflows/prod_ci_citizen-auth.yml
- .github/workflows/prod_drift_citizen-auth.yml
- src/domains/citizen-auth-common/api/io_lollipop/v1/_openapi.yaml
- Fix server url in Lollipop openapi
- Update `pagopa/github-self-hosted-runner-azure-create-action` tag
---
> fix: Fix server url in Lollipop openapi

- src/domains/citizen-auth-app/04_function_lollipop.tf
- src/domains/citizen-auth-common/03_apim.tf
- src/domains/citizen-auth-common/README.md
see commit history
Add a secret to store the primary key of the pagopa apim subscription used by lollipop function to retrieve an assertion.
---
> Add secret for first lollipop subscription key

- src/domains/sign/io_sign_issuer_func.tf
- src/domains/sign/io_sign_user_func.tf
- src/domains/sign/key_vault.tf
This PR adds the necessary resources to `io-sign` for the integration of SelfCare.
- Added `SelfCareEventHubConnectionString` to env-vars and keyvault
- Added `SelfCareApiBasePath` to env-var s
- Added `SelfCareApiKey` to env-vars and keyvault
- Added `SlackApiBasePath` to env-vars 
- Added `SlackApiToekn` to env-vars and keyvault
- [X No
Depends on #458 
---
> [SFEQS-1463]: Add SelfCare integration to `io-sign`

- src/domains/sign/io_sign_user_func.tf
- src/domains/sign/key_vault.tf
This PR add lollipop config to `io-func-sign-user` envvar.
- Add LollipopApiBasePath
- Add LollipopApiKey from KV
---
> chore: Add lollipop config to `io-sign`

- src/domains/citizen-auth-common/03_storage.tf
- src/domains/citizen-auth-common/README.md
- upgrade to storage account 6.1.0 module to avoid unwanted changes using customer key
- set public network access to false to restrict internet access
---
> fix: Upgrade Storage to latest version to avoid unwanted changes

- src/domains/sign/io_sign_issuer_func.tf
Add functions triggered by `cosmos` and `EventHub` to `staging_disabled`
---
> fix: Add triggered functions to `staging_disabled`

- src/domains/citizen-auth-common/05_database.tf
- src/domains/citizen-auth-common/99_variables.tf
- src/domains/citizen-auth-common/README.md
- src/domains/citizen-auth-common/env/prod/terraform.tfvars
Increase `max_throughput` from `1000` to `3000` for `lollipop-pubkeys` collection on Cosmos DB
`max_throughput` and `ttl` for citizen_auth cosmos database are configured via vars.
The production load generated by IO App logins require more RU for cosmos in lollipop database collection.
---
> [#IOCIT-377] Increase autoscale RU value for cosmos lollipop pubkeys

- src/domains/sign/io_sign_user_func.tf
- src/domains/sign/key_vault.tf
Add Namirial (QTSP) test environment to `io-sign`
Depends on #502 
---
> feat: Add Namirial test environment for `io-sign`

- src/domains/sign/apim.tf
- src/domains/sign/io_sign_user_func.tf
- src/domains/sign/key_vault.tf
- Removed unused `SpidAssertionMock` var
- Fixed Namirial endpoint
---
> chore: Remove unused resources for `io-sign` and change qtsp url

- src/domains/sign/api/issuer/v1/get_signer_by_fiscal_code_policy/policy.xml
- src/domains/sign/api_product/sign/_base_policy.xml
- src/domains/sign/apim.tf
- src/domains/sign/io_sign_user_func.tf
Adds a policy to the `getSignerByFiscalCode` endpoint to filter requests based on authorized fiscal codes. In particular, if the issuer uses a test environment, it can contact the `getSignerByFiscalCode` endpoint only with allowed fiscal code.
- Added `io-sign-cosmosdb-issuer-issuers-name` named value
- Added custom policy to `getSignerByFiscalCode`
---
> feat: [SFEQS-1543] Add APIM policy to `getSignerByFiscalCode`

- src/domains/sign/io_sign_user_func.tf
Change QTSP production endpoint for io-sign
---
> chore: Change QTSP prod url for io-sign

- src/domains/sign/landing.tf
This PR drops google refs in the CSP cause we need to avoid to hit Google server directly (and his cookies).
- Change CSP dropping google.com
GDRP's best practice
---
> [SFEQS-1673] FIX: drop google hosts from permitted

- src/core/assets_cdn.tf
1. Set `Access-Control-Allow-Origin` header to `*` for resources served from `/sign` path
the `io-sign` files, served by our CDN, will be embedded in issuers websites, so they should be downloadable from all origins
---
> feat: [SFEQS-1645] Add Access-Control-Allow-Origin header on Assets CDN

- src/core/README.md
- src/core/app_messages.tf
- src/core/monitor.tf
Create a new Redis `v6` for `fn-app-messages`
To avoid downtime on Redis migration from `v4` to `v6`, we are creating a new instance for Redis and later on another PR we change the binding to the new Redis instance.
---
> [#IOPID-207] Create a new Redis v6 resource for fn-app-messages

- src/core/README.md
- src/core/app_messages.tf
Update configuration for `fn-app-messages` pointing to the new Redis V6 cache
Remove old Redis V4 cache
The Redis V4 is deprecated by Microsoft Azure, we need to upgrade the Redis version to V6
---
> [#IOPID-207] Remove Redis V4 cache fn-app-messages

- src/core/devportal.tf
- src/core/selfcare.tf
We have a feature _(manage key)_ that we'll enable for all IO Backoffice users _(Developer Portal and Selfcare)._
Changing _**MANAGE_FLOW_ENABLE_USER_LIST**_ config key to "*" value, we will open the feature to everyone.
This PR is intended to make that change.
---
> [#IOPAE-348] Open IO Backoffice Manage Key to everyone

- src/core/apim.tf
- src/core/apim_v2.tf
- Set apim capacity alarm to 60%
The alarm's threshold is too low
---
> Refine APIM capacity alarm threshold

- src/domains/ioweb-common/10_spid_login.tf
- add `  vnet_integration = true` to app service configuration
Enable vnet_integration for hub-spid-login app service for making it communicate with Redis
---
> fix:[#IOPID-579] Enable vnet_integration for hub-spid-login app service

- src/domains/citizen-auth-app/06_storage.tf
- src/domains/citizen-auth-app/07_function_fast_login.tf
- src/domains/citizen-auth-app/README.md
Add a `data` into `citizen_auth` to refers common storage.
Add new ENV var in `fn-fast-login` with the connection string to the storage.
The `data` can be used only after the resource is created.
---
> [#IOPID-279] Link storage to fn-fast-login

- src/domains/ioweb-app/06_function_ioweb_profile.tf
- src/domains/ioweb-common/01_network.tf
- src/domains/ioweb-common/03_storage.tf
- src/domains/ioweb-common/README.md
- Add missing private endpoint to `iopweuiowebspidlogsst`, to allow gh action to access/edit containers 
---
> fix: Add missing private endpoint to `iopweuiowebspidlogsst `

- src/core/app_messages.tf
Moved FF to canary users, and made a regex that takes 0.4% of fiscal codes in production
We need to reach the whole user base in taking messages from the view calculated from fn-messages-cqrs.
After a year testing with betatesters we are ready to move to canary users.
Enabling canary users increases the impact of our tests, if something goes wrong will go back to betatester.
> [#IOCOM-504] Enable canary for messages from view.

- src/domains/citizen-auth-app/02_security.tf
- src/domains/citizen-auth-app/07_function_fast_login.tf
- src/domains/citizen-auth-app/README.md
> [#IOPID-757] add new required env variables in functions-fast-login

- src/core/README.md
- src/core/app_backend.tf
- src/core/storage_locked_profiles.tf
- src/core/storage_profile_locked.tf
- Add new locked profiles storage, with `lockedprofiles` table
- Update appbackend env variables with `LOCKED_PROFILES_STORAGE_CONNECTION_STRING` and `LOCKED_PROFILES_TABLE_NAME `
Disable login for users with profile in lock state
---
> [#IOPID-859] Add new locked profiles storage

- src/domains/ioweb-app/api/bff/policy.xml
Add an inbound policy to `IO Web - Bff` API group on `APIM v2`
Client needs to perform requests with CORS policy enabled
---
> [IO-PID] 685: Enable CORS policy on IO Web - Bff API group

- src/core/.terraform.lock.hcl
- src/core/README.md
- src/core/apim_io_services_api.tf
- src/core/apim_v2_io_services_api.tf
We recently removed the deprecated createService API and now we are removing the limit policy that was connected to that API
---
> Remove create service policy resource from apim

- src/domains/ioweb-app/06_function_ioweb_profile.tf
- src/domains/ioweb-common/06_cdn.tf
[fix magic link base url](https://github.com/pagopa/io-infra/commit/65d24de2edb966610a8907faa16d670ae33047d4)
[fix CDN 404 link](https://github.com/pagopa/io-infra/pull/707/commits/bf7d8c76b749b61ba308e4f217d5305c0328c06a)
---
> [#IOPID-945] fix: magic link base url

- src/core/00_github_runner.tf
- src/core/README.md
Add a container job for io-sign repository
A single PAT owned by `io-pagopa-github-bot` account, can handle self hosted runners on both io-infra and io-sign repositories. This PR adds the infrastructure needed to run pipelines on io-sign repository
---
> Add GitHub runner on container apps for io-sign

- src/domains/ioweb-common/10_spid_login.tf
Set `CIE_URL` and `IDP_METADATA_URL` to  point internal service
---
> [#IOPID-980] Use internal service for Spid/CIE metadata for ioapp login

- src/domains/messages-common/api/io-backend-notification/v1/_base_policy.xml
- src/domains/messages-common/api/service-messages/v1/_base_policy.xml
- src/domains/payments-common/api/payments_updater/v1/_base_policy.xml
- messages-common APIM policy
- payments-common APIM policy
This PR refactors APIM policy to ensure all production's traffic is routed correctly through AKS web-prod01 cluster.
Beta cluster is going to be replaced by another instance with k8s LTS version (1.27.3)
---
> [#IOPLT-228] - Remove routing to AKS beta cluster

- src/domains/messages-common/api/io-backend-notification/v1/_base_policy.xml
- src/domains/messages-common/api/service-messages/v1/_base_policy.xml
- src/domains/payments-common/api/payments_updater/v1/_base_policy.xml
- Re-Enabling weu-beta routing in `messages` domain
- Re-Enabling weu-beta routing in `payments` domain
This PR is intended for re-enabling production traffic routing through weu-beta AKS cluster after the migration to Kubernetes LTS version.
---
> [#IOPLT-232] Re-Enable routing through Beta AKS

- src/domains/citizen-auth-app/06_storage.tf
- src/domains/citizen-auth-app/README.md
- src/domains/citizen-auth-common/.terraform.lock.hcl
- src/domains/citizen-auth-common/01_network.tf
- src/domains/citizen-auth-common/03_storage.tf
- src/domains/citizen-auth-common/README.md
Added storage account and storage table for unique emails
---
> [#IOPID-1023] Created unique emails storage account and table storage

- src/domains/ioweb-app/api/bff/post_unlockusersession_policy/policy.xml
Update the `UnlockUserSession` API policy using as counting key the `fiscal_code` contained inside the JWT instead of the whole token.
To prevent parallelization by the attacker with many logins, the rate-limit must verify the fiscal_code contained inside the JWT.
---
> [#IOPID-748] rate-limit UnlockUserSession based on CF

- src/core/function_app.tf
- src/domains/citizen-auth-common/03_storage.tf
- src/domains/citizen-auth-common/README.md
1. Updated `uniqueEmails` storage table name with `profileEmails`
2. Disabled `OnProfileUpdate` function both on staging and production slot
When triggered by cosmosDB change feed, the `OnProfileUpdate` function will populate the storage table `profileEmails`. So we need to disable the staging slot and enable the production slot only at the right moment
---
3. select PR branch
4. wait for approval
> [#IOPID-1191] Disabled OnProfileUpdate function

- src/core/README.md
- src/core/azure_devops_agent.tf
Upgrade modules of Azure DevOps agents
`azdoa_li`:
The resource doesn't exist on Azure, however it is stored in the actual state file. Behind the scene, this was a `null_resource` in v4.1.15 but now it's `azurerm`. Terraform will try to recreate it
`azdoa_li_infra`:
no changes
`azdoa_loadtest_li`:
Same as `azdoa_li`, but it does actually exist on Azure, so Terraform wants to replace it.
If these diffs are ok, before merging I shall remove from state the 2 null resources and:
- create `azdoa_li`
- import `azdoa_loadtest_li` into the state - if possible
EDIT:
Importing `azdoa_loadtest_li` doesn't prevent the recreation of the resource. It seems that lot of properties would change:
<details>
<summary>Terraform Plan</summary>
-/+ resource …
> [EC-6] Upgrade Azure DevOps agent modules

- src/domains/messages-common/03_database.tf
- src/domains/messages-common/README.md
Added a new cosmosdb to store remote content related data.
We need to segregate remote content related data in another db, on which we will restrict access and enable cryptography at rest.
---
> [#IOCOM-728] Added cosmos db for remote content

- src/core/README.md
- src/core/app_messages.tf
- src/core/data.tf
- src/core/function_app.tf
- src/core/function_assets_cdn.tf
- src/core/function_cgn.tf
Added 3 remote content cosmos properties
Added TTL for caching services data
Made some winter cleaning removing useless properties
We need to allow app-messages-fn to connect to a new DB and have a wait to change cache TTL without redeploying
> [#IOCOM-734] Added configuration properties to store Remote Content's cosmos connection data

- src/core/.terraform.lock.hcl
- src/core/99_main.tf
- src/core/README.md
- src/core/app_backend.tf
- src/core/continua_dynamiclink.tf
- src/core/function_devportal_service_data.tf
- src/core/redis.tf
Upgrade azurerm to 3.84
Update app service and function to newer TF module to support new (mandatory) property. [Ref](https://github.com/pagopa/terraform-azurerm-v3/pull/201)
Upgrading the module `postgres_flexible_server` required a more recent `azurerm` provider version, so these two changes had to be done in parallel.
At this time, 3.84 is the most recent version
---
> [EC-38] Upgrade postgres module and azurerm version of core config

- src/domains/ioweb-common/10_spid_login.tf
This PR depends on https://github.com/pagopa/io-infra/pull/778
Switch to newly created immutable spid log storage
---
> [#IOPID-1221] Switch to new immutable storage for spid logs

- .identity/04_github_identity.tf
- .identity/99_variables.tf
- .identity/env/prod/terraform.tfvars
`io-infra` managed identity is now federated with `io-infra` repository only. Removed both `io-sign` and `io-services-metadata` as discussed [here](https://github.com/pagopa/io-infra/pull/745#discussion_r1410721348)
`io-infra` requires a big set of permissions and these should be used by `io-infra` repository only
---
> [EC-43] Remove other repos federation from io-infra managed identity

- src/domains/citizen-auth-common/03_storage.tf
- src/domains/citizen-auth-common/README.md
- src/domains/ioweb-common/03_storage.tf
- src/domains/ioweb-common/06_cdn.tf
- src/domains/ioweb-common/README.md
Remove old mutable storage for:
- io-web spid logs
- LV audit log
The audit log are now stored in immutable storage. The old mutable storage can be deleted after the data migration.
The data migration was completed manually.
---
> [#IOPID-1279] Remove old mutable storage after migration

- .github/workflows/ioweb_prod_cd.yml
- .github/workflows/prod_cd_citizen-auth.yml
Add `checkout` steps to CD pipelines
New runners are randomly created so code must be checked out every time
---
> Add missing 'checkout' step to CD pipelines

- src/core/app_messages.tf
- src/core/function_admin.tf
- src/core/function_eucovidcert.tf
Add 2 new envs to allow fn-admin to connect Lock Profile storage
The fn-admin must delete the profile locks when a delete profile operation was requested.
---
**This PR was applied locally only on target resources `module.function_admin` and `module.function_admin_staging_slot`**. The other misconfigured resources will be fixed on another PR.
> [#IOPID-1125] Add ENV in fn-admin to Lock Profile table storage

- .github/workflows/ioweb_prod_cd.yml
- .github/workflows/prod_cd_citizen-auth.yml
Upload all TF plan files
Plan outputs must be passed between jobs since they are arbitrary
---
> [EC-68] Fix Terraform Plan output paths

- .github/workflows/ioweb_prod_cd.yml
- .github/workflows/prod_cd_citizen-auth.yml
Add steps to perform TF init
TF wasn't initialized was missing due to ephemeral runners
---
> [EC-68] Force TF init in CD pipelines

- .github/workflows/ioweb_prod_cd.yml
- .github/workflows/prod_cd_citizen-auth.yml
Replace terraform.sh apply with terraform apply
terraform.sh always add a -var flag and this is not supported when plan is saved to a file
---
> [EC-68] Replace terraform.sh with tf commands

- src/core/99_variables.tf
- src/core/README.md
- src/core/function_services.tf
Add autoscale capabilities to CosmosDB collection `subscription-cidrs`
---
> Add autoscale capabilities to subscription_cidrs collection

- src/domains/ioweb-common/03_storage.tf
- src/domains/ioweb-common/README.md
Use only one resource for the two rule of Azure Storage Management Policy.
Using two different Azure Storage Management Policy for different rule create a conflict where only one is created, and the second will override the first declare. This PR add the two rules inside the same policy.
---
> Fix Policy on the audit log storage

- src/core/env/prod/terraform.tfvars
Restore minimun instances for `fn-app-async` to 2 after seeding "Univocità Indirizzi Email"
After the seeding for the table storage of unique email is completed we restore the number of minimum instances of `fn-app-async` to reduce costs.
---
The change was made by the Azure Portal because the current status of infra is disaligned on some resource (`app-gateway`)
> [#IOPID-1356] Restore minimum instances fn-app afeter seeding

- src/core/99_variables.tf
- src/core/README.md
- src/core/app_messages.tf
- src/core/assets_cdn.tf
- src/core/function_devportal_service_data.tf
Added some env variables to functions-app-messages 
We added a map to get a default remote content configuration for all Remote Contents sent before February 2024.
> [#IOCOM-1033] Added env var to map a fallback value from internal services to remote content configs

- src/domains/messages-common/03_database.tf
- src/domains/messages-common/README.md
Added the collection `user-configurations`
We need this collection to save the relation between users and configurations and avoid expensive cross partition queries during a list operation over the `message-configuration` collection that is versioned and partitioned by `configurationId`.
> [#IOCOM-1035] Added support collection

- src/core/README.md
- src/core/function_admin.tf
[add new env var INSTANT_DELETE_ENABLED_USERS](https://github.com/pagopa/io-infra/commit/8f2da616c6ba4a7ef6e120ca8b50e1bf30a3f2c0)
Enable instant delete of allowed users
⚠️  The update of `ALLOW_PAGOPA_IP_SOURCE_RANGE` is a deliberate and desired update
---
> [#IOPID-1470] Add new env var `INSTANT_DELETE_ENABLED_USERS`

- src/core/appgateway.tf
- [reduce response time sensibility to Medium](https://github.com/pagopa/io-infra/commit/be5065b56ce1f64be7a9c47b287d525c1fa0822a)
- [increase window size to 15M](https://github.com/pagopa/io-infra/pull/901/commits/313d56bf7bb405e2bccb400c0959f882f8aa4bf8)
False alert are triggered for some listeners.
---
> Reduce `appgateway` response time alert sensibility to `Medium` 

- src/domains/sign/io_sign_user_func.tf
The function app `io-p-sign-user-func` is unhealthy in the staging slot
---
> fix: Added IoServicesConfigurationId env variable to io-sign-user-func

- .github/labeler.yml
- src/core/README.md
- src/core/devportal.tf
- src/core/function_devportal_service_data.tf
- src/core/function_subscription_migrations.tf
- src/core/selfcare.tf
- src/domains/selfcare/_modules/resource_groups/main.tf
- src/domains/selfcare/_modules/resource_groups/outputs.tf
- src/domains/selfcare/_modules/resource_groups/resource_group_selfcare_be.tf
- src/domains/selfcare/_modules/resource_groups/resource_group_selfcare_fe.tf
- src/domains/selfcare/_modules/resource_groups/variables.tf
- src/domains/selfcare/prod/westeurope/.terraform.lock.hcl
- src/domains/selfcare/prod/westeurope/README.md
- src/domains/selfcare/prod/westeurope/locals.tf
- src/domains/selfcare/prod/westeurope/main.tf
- src/domains/selfcare/prod/westeurope/resource_groups.tf
Move selfcare resource groups from core to their own config
---
> [EC-216] Move io-selfcare resource groups in their own configuration

- .github/labeler.yml
- .github/workflows/eucovidcert_cd.yaml
- .github/workflows/eucovidcert_ci.yaml
- src/core/README.md
- src/core/function_eucovidcert.tf
- src/domains/eucovidcert/_modules/resource_groups/main.tf
- src/domains/eucovidcert/_modules/resource_groups/outputs.tf
- src/domains/eucovidcert/_modules/resource_groups/resource_group_eucovidcert.tf
- src/domains/eucovidcert/_modules/resource_groups/variables.tf
- src/domains/eucovidcert/prod/westeurope/.terraform.lock.hcl
- src/domains/eucovidcert/prod/westeurope/README.md
- src/domains/eucovidcert/prod/westeurope/locals.tf
- src/domains/eucovidcert/prod/westeurope/main.tf
- src/domains/eucovidcert/prod/westeurope/resource_groups.tf
Move resource group
CI/CD workflows
---
> [EC-217] Move eucovidcert resource group to their own configuration

- src/core/README.md
- src/core/function_eucovidcert.tf
- src/domains/eucovidcert/_modules/storage_accounts/main.tf
- src/domains/eucovidcert/_modules/storage_accounts/outputs.tf
- src/domains/eucovidcert/_modules/storage_accounts/storage_account_eucovidcert.tf
- src/domains/eucovidcert/_modules/storage_accounts/variables.tf
- src/domains/eucovidcert/prod/westeurope/.terraform.lock.hcl
- src/domains/eucovidcert/prod/westeurope/README.md
- src/domains/eucovidcert/prod/westeurope/storage_accounts.tf
Move EUCovidCert storage accounts to their own module
---
> [EC-217] Move EUCovidCert storage accounts to their own module

- src/domains/sign/monitoring.tf
Now the `io-p-sign-rejected-requests` alarm is triggered only for the rejected signature request in the production environment.
I've created the `io-p-sign-rejected-test-requests` alarm that is triggered only for those in testing and whose only action is to send a message to the FCI Slack group
---
> [SFEQS-2145] Added io-p-sign-rejected-test-requests alert rule and updated io-p-sign-rejected-requests

- src/domains/messages-app/12_function_service_messages.tf
- src/domains/messages-app/README.md
Referenced github runner subnet.
Added github runner subnet to staging slot to allow healthcheck.
Deploy from gihub actions needs to do a healthcheck before swapping staging and prod slots.
> [#IOCOM-1221] Enabled runner subnet on staging slot

- src/domains/messages-app/10_function_messages.tf
Add two scaling rules to the existing one:
- set minimum instances to 4 during the time range 19:50-21:00
- set minimum instances to 2 during the time range 01:00-05:00
Improving scaling automation for sudden spikes. So we scale in advance
---
> [EC-268] Add scheduled autoscale rules for messages function apps

- .pre-commit-config.yaml
- Re-enabled the terraform_validate pre-commit check.
- Excluded all paths that contain the "modules" or "_modules" folder from the terraform_validate check
With the introduction of the repository structure suggested in this [RFC](https://pagopa.atlassian.net/wiki/spaces/ENG/pages/910492147/RFC-ENG+Riorganizzazione+configurazioni+Terraform), the terraform_validate pre-commit check began failing for each child module with the following error:
```
This configuration requires provider registry.terraform.io/hashicorp/azurerm, but that provider isn't available. You may be able to install it automatically by running:
terraform init
```
The issue is caused by the recursive run of "terraform validate" commands both on root and child modules. The latter, by nature, shouldn't be initialized and …
> [EC-307] Fix for terraform_validate pre-commit

- src/domains/functions/README.md
- src/domains/functions/data.tf
- src/domains/functions/function_admin.tf
Switch source queue for fn-admin/SanitizeProfileEmail to the newly created in `iopitnauthmntst01` ITN Storage
> Switch profiles-to-sanitize queue to new ITN auth maintenance storage

- src/common/_modules/cosmos_api/locals.tf
- src/common/_modules/function_services/function-app/storage-account.tf
needed to match configuration of `iopservicesfn1sdt` after migrating to itn
> [#IOPLT-1347]add lifecycle management rule on iopitnfuncsvcst01 storage

- src/common/_modules/app_backend/locals.tf
- src/common/prod/westeurope.tf
Scaleup all `appbackend` plans to `P2V3` after load test results.
Enable `PM2` startup command for all `appbackend`.
> [#IOPLT-1353] Scaleup appbackend to P2V3 and enable PM2
